//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.02 at 01:05:27 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComparisonOperator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ComparisonOperator">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GreaterThanOrEqualToThreshold"/>
 *     &lt;enumeration value="GreaterThanThreshold"/>
 *     &lt;enumeration value="LessThanThreshold"/>
 *     &lt;enumeration value="LessThanOrEqualToThreshold"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ComparisonOperator")
@XmlEnum
public enum ComparisonOperator {

    @XmlEnumValue("GreaterThanOrEqualToThreshold")
    GREATER_THAN_OR_EQUAL_TO_THRESHOLD("GreaterThanOrEqualToThreshold"),
    @XmlEnumValue("GreaterThanThreshold")
    GREATER_THAN_THRESHOLD("GreaterThanThreshold"),
    @XmlEnumValue("LessThanThreshold")
    LESS_THAN_THRESHOLD("LessThanThreshold"),
    @XmlEnumValue("LessThanOrEqualToThreshold")
    LESS_THAN_OR_EQUAL_TO_THRESHOLD("LessThanOrEqualToThreshold");
    private final String value;

    ComparisonOperator(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComparisonOperator fromValue(String v) {
        for (ComparisonOperator c: ComparisonOperator.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
