//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 12:27:12 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateKeyPairType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateKeyPairType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KeyPairName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KeyPairDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateKeyPairType", propOrder = {
    "keyPairName",
    "keyPairDesc",
    "region"
})
public class CreateKeyPairType {

    @XmlElement(name = "KeyPairName", required = true)
    protected String keyPairName;
    @XmlElement(name = "KeyPairDesc", required = true)
    protected String keyPairDesc;
    @XmlElement(name = "Region", required = true)
    protected String region;

    /**
     * Gets the value of the keyPairName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyPairName() {
        return keyPairName;
    }

    /**
     * Sets the value of the keyPairName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyPairName(String value) {
        this.keyPairName = value;
    }

    /**
     * Gets the value of the keyPairDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyPairDesc() {
        return keyPairDesc;
    }

    /**
     * Sets the value of the keyPairDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyPairDesc(String value) {
        this.keyPairDesc = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

}
