//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.04 at 03:24:31 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateDBSnapshotDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateDBSnapshotDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBSnapshot" type="{}DBSnapshotType"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateDBSnapshotDetailsType", propOrder = {
    "dbSnapshot",
    "status"
})
public class CreateDBSnapshotDetailsType {

    @XmlElement(name = "DBSnapshot", required = true)
    protected DBSnapshotType dbSnapshot;
    @XmlElement(name = "Status", required = true)
    protected String status;

    /**
     * Gets the value of the dbSnapshot property.
     * 
     * @return
     *     possible object is
     *     {@link DBSnapshotType }
     *     
     */
    public DBSnapshotType getDBSnapshot() {
        return dbSnapshot;
    }

    /**
     * Sets the value of the dbSnapshot property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBSnapshotType }
     *     
     */
    public void setDBSnapshot(DBSnapshotType value) {
        this.dbSnapshot = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
