//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.21 at 05:35:52 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.amazonaws.services.rds.model.DBInstance;


/**
 * <p>Java class for DBInstanceListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DBInstanceListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBInstance" type="{}DBInstanceType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DBInstanceListType", propOrder = {
    "dbInstance"
})
public class DBInstanceListType {

    @XmlElement(name = "DBInstance", required = true)
    protected List<DBInstanceType> dbInstance;

    public DBInstanceListType(){}
    public DBInstanceListType(List<DBInstance> dbInstances) {
    	List<DBInstanceType> dbInstanceTypeList = new ArrayList<DBInstanceType>(); 
    	DBInstanceType dbInstanceType;
    	for (DBInstance dbInstance : dbInstances){
    		dbInstanceType = new DBInstanceType(dbInstance);
    		dbInstanceTypeList.add(dbInstanceType);
    	}
    	this.dbInstance = dbInstanceTypeList;
	}

	/**
     * Gets the value of the dbInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dbInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDBInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DBInstanceType }
     * 
     * 
     */
    public List<DBInstanceType> getDBInstance() {
        if (dbInstance == null) {
            dbInstance = new ArrayList<DBInstanceType>();
        }
        return this.dbInstance;
    }

}
