//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.21 at 05:35:52 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DBSecurityGroups complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DBSecurityGroups">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBSecurityGroup" type="{}DBSecurityGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DBSecurityGroups", propOrder = {
    "dbSecurityGroup"
})
public class DBSecurityGroups {

    @XmlElement(name = "DBSecurityGroup", required = true)
    protected List<DBSecurityGroup> dbSecurityGroup;

    public DBSecurityGroups(){}
	public DBSecurityGroups(List<com.amazonaws.services.rds.model.DBSecurityGroup> dbSecurityGroups) {
		
		DBSecurityGroup dbSecGrpType;
		List<DBSecurityGroup> dBSecGrpList;
		dBSecGrpList = new ArrayList<DBSecurityGroup>();
		for (com.amazonaws.services.rds.model.DBSecurityGroup dbSecGrp : dbSecurityGroups ) {
			dbSecGrpType = new DBSecurityGroup(dbSecGrp);
			dBSecGrpList.add(dbSecGrpType);
		}
		
		this.dbSecurityGroup = dBSecGrpList;
	}

	/**
     * Gets the value of the dbSecurityGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dbSecurityGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDBSecurityGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DBSecurityGroup }
     * 
     * 
     */
    public List<DBSecurityGroup> getDBSecurityGroup() {
        if (dbSecurityGroup == null) {
            dbSecurityGroup = new ArrayList<DBSecurityGroup>();
        }
        return this.dbSecurityGroup;
    }

	public void setDbSecurityGroup(List<DBSecurityGroup> dbSecurityGroup) {
		this.dbSecurityGroup = dbSecurityGroup;
	}
    
    

}
