//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.27 at 04:04:49 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescribeLoadBalancersResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescribeLoadBalancersResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoadBalancerDescriptions" type="{}LoadBalancerDescriptionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescribeLoadBalancersResultType", propOrder = {
    "loadBalancerDescriptions"
})
public class DescribeLoadBalancersResultType {

    @XmlElement(name = "LoadBalancerDescriptions")
    protected LoadBalancerDescriptionsType loadBalancerDescriptions;

    /**
     * Gets the value of the loadBalancerDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link LoadBalancerDescriptionsType }
     *     
     */
    public LoadBalancerDescriptionsType getLoadBalancerDescriptions() {
        return loadBalancerDescriptions;
    }

    /**
     * Sets the value of the loadBalancerDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadBalancerDescriptionsType }
     *     
     */
    public void setLoadBalancerDescriptions(LoadBalancerDescriptionsType value) {
        this.loadBalancerDescriptions = value;
    }

}
