//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.06 at 02:21:36 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescribeAutoScalingGroupsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescribeAutoScalingGroupsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AutoScalingGroupNames" type="{}AutoScalingGroupNamesType" minOccurs="0"/>
 *         &lt;element name="NextToken" type="{}XmlString" minOccurs="0"/>
 *         &lt;element name="MaxRecords" type="{}MaxRecords" minOccurs="0"/>
 *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescribeAutoScalingGroupsType", propOrder = {
    "autoScalingGroupNames",
    "nextToken",
    "maxRecords",
    "region"
})
public class DescribeAutoScalingGroupsType {

    @XmlElement(name = "AutoScalingGroupNames")
    protected AutoScalingGroupNamesType autoScalingGroupNames;
    @XmlElement(name = "NextToken")
    protected String nextToken;
    @XmlElement(name = "MaxRecords")
    protected BigInteger maxRecords;
    @XmlElement(name = "Region", required = true)
    protected String region;

    /**
     * Gets the value of the autoScalingGroupNames property.
     * 
     * @return
     *     possible object is
     *     {@link AutoScalingGroupNamesType }
     *     
     */
    public AutoScalingGroupNamesType getAutoScalingGroupNames() {
        return autoScalingGroupNames;
    }

    /**
     * Sets the value of the autoScalingGroupNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutoScalingGroupNamesType }
     *     
     */
    public void setAutoScalingGroupNames(AutoScalingGroupNamesType value) {
        this.autoScalingGroupNames = value;
    }

    /**
     * Gets the value of the nextToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextToken() {
        return nextToken;
    }

    /**
     * Sets the value of the nextToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextToken(String value) {
        this.nextToken = value;
    }

    /**
     * Gets the value of the maxRecords property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxRecords() {
        return maxRecords;
    }

    /**
     * Sets the value of the maxRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxRecords(BigInteger value) {
        this.maxRecords = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

}
