//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.25 at 02:50:33 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescribeLoadBalancersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescribeLoadBalancersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoadBalancerNames" type="{}LoadBalancerNames" minOccurs="0"/>
 *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescribeLoadBalancersType", propOrder = {
    "loadBalancerNames",
    "region"
})
public class DescribeLoadBalancersType {

    @XmlElement(name = "LoadBalancerNames")
    protected LoadBalancerNamesType loadBalancerNames;
    @XmlElement(name = "Region", required = true)
    protected String region;

    /**
     * Gets the value of the loadBalancerNames property.
     * 
     * @return
     *     possible object is
     *     {@link LoadBalancerNamesType }
     *     
     */
    public LoadBalancerNamesType getLoadBalancerNames() {
        return loadBalancerNames;
    }

    /**
     * Sets the value of the loadBalancerNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadBalancerNamesType }
     *     
     */
    public void setLoadBalancerNames(LoadBalancerNamesType value) {
        this.loadBalancerNames = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

}
