//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.09 at 07:45:32 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ec2InstanceResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ec2InstanceResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InstanceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InstanceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KeyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LaunchTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Monitoring" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AvailabilityZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PublicDnsName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrivateDnsName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PublicIpAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrivateIpAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Architecture" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KernelId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RootDeviceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RootDeviceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VirtualizationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LoadBalancerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ec2InstanceResponse", propOrder = {
    "imageId",
    "instanceId",
    "instanceType",
    "keyName",
    "state",
    "launchTime",
    "monitoring",
    "availabilityZone",
    "publicDnsName",
    "privateDnsName",
    "publicIpAddress",
    "privateIpAddress",
    "architecture",
    "kernelId",
    "rootDeviceName",
    "rootDeviceType",
    "virtualizationType",
    "loadBalancerName",
    "status",
    "region"
})
public class Ec2InstanceResponse {

    @XmlElement(name = "ImageId")
    protected String imageId;
    @XmlElement(name = "InstanceId", required = true)
    protected String instanceId;
    @XmlElement(name = "InstanceType", required = true)
    protected String instanceType;
    @XmlElement(name = "KeyName")
    protected String keyName;
    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlElement(name = "LaunchTime", required = true)
    protected String launchTime;
    @XmlElement(name = "Monitoring")
    protected String monitoring;
    @XmlElement(name = "AvailabilityZone", required = true)
    protected String availabilityZone;
    @XmlElement(name = "PublicDnsName")
    protected String publicDnsName;
    @XmlElement(name = "PrivateDnsName")
    protected String privateDnsName;
    @XmlElement(name = "PublicIpAddress")
    protected String publicIpAddress;
    @XmlElement(name = "PrivateIpAddress")
    protected String privateIpAddress;
    @XmlElement(name = "Architecture")
    protected String architecture;
    @XmlElement(name = "KernelId")
    protected String kernelId;
    @XmlElement(name = "RootDeviceName")
    protected String rootDeviceName;
    @XmlElement(name = "RootDeviceType")
    protected String rootDeviceType;
    @XmlElement(name = "VirtualizationType")
    protected String virtualizationType;
    @XmlElement(name = "LoadBalancerName")
    protected String loadBalancerName;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "Region", required = true)
    protected String region;

    /**
     * Gets the value of the imageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * Sets the value of the imageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageId(String value) {
        this.imageId = value;
    }

    /**
     * Gets the value of the instanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * Sets the value of the instanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceId(String value) {
        this.instanceId = value;
    }

    /**
     * Gets the value of the instanceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceType() {
        return instanceType;
    }

    /**
     * Sets the value of the instanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceType(String value) {
        this.instanceType = value;
    }

    /**
     * Gets the value of the keyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * Sets the value of the keyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyName(String value) {
        this.keyName = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the launchTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaunchTime() {
        return launchTime;
    }

    /**
     * Sets the value of the launchTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaunchTime(String value) {
        this.launchTime = value;
    }

    /**
     * Gets the value of the monitoring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonitoring() {
        return monitoring;
    }

    /**
     * Sets the value of the monitoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonitoring(String value) {
        this.monitoring = value;
    }

    /**
     * Gets the value of the availabilityZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityZone() {
        return availabilityZone;
    }

    /**
     * Sets the value of the availabilityZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityZone(String value) {
        this.availabilityZone = value;
    }

    /**
     * Gets the value of the publicDnsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicDnsName() {
        return publicDnsName;
    }

    /**
     * Sets the value of the publicDnsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicDnsName(String value) {
        this.publicDnsName = value;
    }

    /**
     * Gets the value of the privateDnsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateDnsName() {
        return privateDnsName;
    }

    /**
     * Sets the value of the privateDnsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateDnsName(String value) {
        this.privateDnsName = value;
    }

    /**
     * Gets the value of the publicIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicIpAddress() {
        return publicIpAddress;
    }

    /**
     * Sets the value of the publicIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicIpAddress(String value) {
        this.publicIpAddress = value;
    }

    /**
     * Gets the value of the privateIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateIpAddress() {
        return privateIpAddress;
    }

    /**
     * Sets the value of the privateIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateIpAddress(String value) {
        this.privateIpAddress = value;
    }

    /**
     * Gets the value of the architecture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchitecture() {
        return architecture;
    }

    /**
     * Sets the value of the architecture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchitecture(String value) {
        this.architecture = value;
    }

    /**
     * Gets the value of the kernelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKernelId() {
        return kernelId;
    }

    /**
     * Sets the value of the kernelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKernelId(String value) {
        this.kernelId = value;
    }

    /**
     * Gets the value of the rootDeviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootDeviceName() {
        return rootDeviceName;
    }

    /**
     * Sets the value of the rootDeviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootDeviceName(String value) {
        this.rootDeviceName = value;
    }

    /**
     * Gets the value of the rootDeviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootDeviceType() {
        return rootDeviceType;
    }

    /**
     * Sets the value of the rootDeviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootDeviceType(String value) {
        this.rootDeviceType = value;
    }

    /**
     * Gets the value of the virtualizationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVirtualizationType() {
        return virtualizationType;
    }

    /**
     * Sets the value of the virtualizationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirtualizationType(String value) {
        this.virtualizationType = value;
    }

    /**
     * Gets the value of the loadBalancerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadBalancerName() {
        return loadBalancerName;
    }

    /**
     * Sets the value of the loadBalancerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadBalancerName(String value) {
        this.loadBalancerName = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

}
