//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 12:27:12 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ec2InstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ec2InstanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AMI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InstanceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AvailabilityZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecurityGroupName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="KeyPair" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UserData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MinInstances" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MaxInstances" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Monitoring" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="LBName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ec2InstanceType", propOrder = {
    "ami",
    "instanceType",
    "region",
    "availabilityZone",
    "securityGroupName",
    "keyPair",
    "userData",
    "minInstances",
    "maxInstances",
    "monitoring",
    "lbName"
})
public class Ec2InstanceType {

    @XmlElement(name = "AMI", required = true)
    protected String ami;
    @XmlElement(name = "InstanceType", required = true)
    protected String instanceType;
    @XmlElement(name = "Region", required = true)
    protected String region;
    @XmlElement(name = "AvailabilityZone", required = true)
    protected String availabilityZone;
    @XmlElement(name = "SecurityGroupName")
    protected List<String> securityGroupName;
    @XmlElement(name = "KeyPair", required = true)
    protected String keyPair;
    @XmlElement(name = "UserData", required = true)
    protected String userData;
    @XmlElement(name = "MinInstances")
    protected int minInstances;
    @XmlElement(name = "MaxInstances")
    protected int maxInstances;
    @XmlElement(name = "Monitoring")
    protected boolean monitoring;
    @XmlElement(name = "LBName", required = true)
    protected String lbName;

    /**
     * Gets the value of the ami property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMI() {
        return ami;
    }

    /**
     * Sets the value of the ami property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMI(String value) {
        this.ami = value;
    }

    /**
     * Gets the value of the instanceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceType() {
        return instanceType;
    }

    /**
     * Sets the value of the instanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceType(String value) {
        this.instanceType = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the availabilityZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityZone() {
        return availabilityZone;
    }

    /**
     * Sets the value of the availabilityZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityZone(String value) {
        this.availabilityZone = value;
    }

    /**
     * Gets the value of the securityGroupName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityGroupName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurityGroupName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSecurityGroupName() {
        if (securityGroupName == null) {
            securityGroupName = new ArrayList<String>();
        }
        return this.securityGroupName;
    }

    /**
     * Gets the value of the keyPair property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyPair() {
        return keyPair;
    }

    /**
     * Sets the value of the keyPair property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyPair(String value) {
        this.keyPair = value;
    }

    /**
     * Gets the value of the userData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserData(String value) {
        this.userData = value;
    }

    /**
     * Gets the value of the minInstances property.
     * 
     */
    public int getMinInstances() {
        return minInstances;
    }

    /**
     * Sets the value of the minInstances property.
     * 
     */
    public void setMinInstances(int value) {
        this.minInstances = value;
    }

    /**
     * Gets the value of the maxInstances property.
     * 
     */
    public int getMaxInstances() {
        return maxInstances;
    }

    /**
     * Sets the value of the maxInstances property.
     * 
     */
    public void setMaxInstances(int value) {
        this.maxInstances = value;
    }

    /**
     * Gets the value of the monitoring property.
     * 
     */
    public boolean isMonitoring() {
        return monitoring;
    }

    /**
     * Sets the value of the monitoring property.
     * 
     */
    public void setMonitoring(boolean value) {
        this.monitoring = value;
    }

    /**
     * Gets the value of the lbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLBName() {
        return lbName;
    }

    /**
     * Sets the value of the lbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLBName(String value) {
        this.lbName = value;
    }

}