//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.09 at 09:38:54 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.automata.cloudcore.xmlbindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Automata_QNAME = new QName("", "Automata");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.automata.cloudcore.xmlbindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AutoScalingGroupsType }
     * 
     */
    public AutoScalingGroupsType createAutoScalingGroupsType() {
        return new AutoScalingGroupsType();
    }

    /**
     * Create an instance of {@link EndpointType }
     * 
     */
    public EndpointType createEndpointType() {
        return new EndpointType();
    }

    /**
     * Create an instance of {@link DBParameterGroupStatusType }
     * 
     */
    public DBParameterGroupStatusType createDBParameterGroupStatusType() {
        return new DBParameterGroupStatusType();
    }

    /**
     * Create an instance of {@link CreateDBInstanceType }
     * 
     */
    public CreateDBInstanceType createCreateDBInstanceType() {
        return new CreateDBInstanceType();
    }

    /**
     * Create an instance of {@link EC2SecurityGroup }
     * 
     */
    public EC2SecurityGroup createEC2SecurityGroup() {
        return new EC2SecurityGroup();
    }

    /**
     * Create an instance of {@link DBSecurityGroupMembershipListType }
     * 
     */
    public DBSecurityGroupMembershipListType createDBSecurityGroupMembershipListType() {
        return new DBSecurityGroupMembershipListType();
    }

    /**
     * Create an instance of {@link ResumeProcessesType }
     * 
     */
    public ResumeProcessesType createResumeProcessesType() {
        return new ResumeProcessesType();
    }

    /**
     * Create an instance of {@link ListenerType }
     * 
     */
    public ListenerType createListenerType() {
        return new ListenerType();
    }

    /**
     * Create an instance of {@link ResumeProcessesResponseType }
     * 
     */
    public ResumeProcessesResponseType createResumeProcessesResponseType() {
        return new ResumeProcessesResponseType();
    }

    /**
     * Create an instance of {@link ReadReplicaDBInstanceIdentifierListType }
     * 
     */
    public ReadReplicaDBInstanceIdentifierListType createReadReplicaDBInstanceIdentifierListType() {
        return new ReadReplicaDBInstanceIdentifierListType();
    }

    /**
     * Create an instance of {@link CreateLBCookieStickinessPolicyType }
     * 
     */
    public CreateLBCookieStickinessPolicyType createCreateLBCookieStickinessPolicyType() {
        return new CreateLBCookieStickinessPolicyType();
    }

    /**
     * Create an instance of {@link IpPermissionType }
     * 
     */
    public IpPermissionType createIpPermissionType() {
        return new IpPermissionType();
    }

    /**
     * Create an instance of {@link IpPermissionSetType }
     * 
     */
    public IpPermissionSetType createIpPermissionSetType() {
        return new IpPermissionSetType();
    }

    /**
     * Create an instance of {@link DescribeLaunchConfigurationsType }
     * 
     */
    public DescribeLaunchConfigurationsType createDescribeLaunchConfigurationsType() {
        return new DescribeLaunchConfigurationsType();
    }

    /**
     * Create an instance of {@link IPRange }
     * 
     */
    public IPRange createIPRange() {
        return new IPRange();
    }

    /**
     * Create an instance of {@link CreateDBSecurityGroupResponse }
     * 
     */
    public CreateDBSecurityGroupResponse createCreateDBSecurityGroupDetailsType() {
        return new CreateDBSecurityGroupResponse();
    }

    /**
     * Create an instance of {@link RunningInstancesItemType }
     * 
     */
    public RunningInstancesItemType createRunningInstancesItemType() {
        return new RunningInstancesItemType();
    }

    /**
     * Create an instance of {@link ListenerDescriptionType }
     * 
     */
    public ListenerDescriptionType createListenerDescriptionType() {
        return new ListenerDescriptionType();
    }

    /**
     * Create an instance of {@link EnabledMetricsType }
     * 
     */
    public EnabledMetricsType createEnabledMetricsType() {
        return new EnabledMetricsType();
    }

    /**
     * Create an instance of {@link DeleteSecurityGroupResponseType }
     * 
     */
    public DeleteSecurityGroupResponseType createDeleteSecurityGroupResponseType() {
        return new DeleteSecurityGroupResponseType();
    }

    /**
     * Create an instance of {@link DescribeSecurityGroupsType }
     * 
     */
    public DescribeSecurityGroupsType createDescribeSecurityGroupsType() {
        return new DescribeSecurityGroupsType();
    }

    /**
     * Create an instance of {@link HealthCheckType }
     * 
     */
    public HealthCheckType createHealthCheckType() {
        return new HealthCheckType();
    }

    /**
     * Create an instance of {@link RestoreDBInstanceFromDBSnapshotResponseType }
     * 
     */
    public RestoreDBInstanceFromDBSnapshotResponseType createRestoreDBInstanceFromDBSnapshotResponseType() {
        return new RestoreDBInstanceFromDBSnapshotResponseType();
    }

    /**
     * Create an instance of {@link InstanceMonitoringType }
     * 
     */
    public InstanceMonitoringType createInstanceMonitoringType() {
        return new InstanceMonitoringType();
    }

    /**
     * Create an instance of {@link CreateLBCookieStickinessPolicyResponse }
     * 
     */
    public CreateLBCookieStickinessPolicyResponse createCreateLBCookieStickinessPolicyDetailsType() {
        return new CreateLBCookieStickinessPolicyResponse();
    }

    /**
     * Create an instance of {@link SecurityGroups }
     * 
     */
    public SecurityGroups createSecurityGroups() {
        return new SecurityGroups();
    }

    /**
     * Create an instance of {@link DBSecurityGroupMembershipType }
     * 
     */
    public DBSecurityGroupMembershipType createDBSecurityGroupMembershipType() {
        return new DBSecurityGroupMembershipType();
    }

    /**
     * Create an instance of {@link DescribeInstancesInfoType }
     * 
     */
    public DescribeInstancesInfoType createDescribeInstancesInfoType() {
        return new DescribeInstancesInfoType();
    }

    /**
     * Create an instance of {@link InstanceLicenseResponseType }
     * 
     */
    public InstanceLicenseResponseType createInstanceLicenseResponseType() {
        return new InstanceLicenseResponseType();
    }

    /**
     * Create an instance of {@link ValueSetType }
     * 
     */
    public ValueSetType createValueSetType() {
        return new ValueSetType();
    }

    /**
     * Create an instance of {@link DeleteDBSecurityGroupResponseType }
     * 
     */
    public DeleteDBSecurityGroupResponseType createDeleteDBSecurityGroupResponseType() {
        return new DeleteDBSecurityGroupResponseType();
    }

    /**
     * Create an instance of {@link AppCookieStickinessPolicyType }
     * 
     */
    public AppCookieStickinessPolicyType createAppCookieStickinessPolicyType() {
        return new AppCookieStickinessPolicyType();
    }

    /**
     * Create an instance of {@link InstanceIdSetType }
     * 
     */
    public InstanceIdSetType createInstanceIdSetType() {
        return new InstanceIdSetType();
    }

    /**
     * Create an instance of {@link DeleteDBSecurityGroupType }
     * 
     */
    public DeleteDBSecurityGroupType createDeleteDBSecurityGroupType() {
        return new DeleteDBSecurityGroupType();
    }

    /**
     * Create an instance of {@link DeleteDBInstanceResponseType }
     * 
     */
    public DeleteDBInstanceResponseType createDeleteDBInstanceResponseType() {
        return new DeleteDBInstanceResponseType();
    }

    /**
     * Create an instance of {@link AddSecurityGroupRuleResponse }
     * 
     */
    public AddSecurityGroupRuleResponse createAddSecurityGroupRuleResponse() {
        return new AddSecurityGroupRuleResponse();
    }

    /**
     * Create an instance of {@link LoadBalancerDescriptionType }
     * 
     */
    public LoadBalancerDescriptionType createLoadBalancerDescriptionType() {
        return new LoadBalancerDescriptionType();
    }

    /**
     * Create an instance of {@link SuspendProcessesResponseType }
     * 
     */
    public SuspendProcessesResponseType createSuspendProcessesResponseType() {
        return new SuspendProcessesResponseType();
    }

    /**
     * Create an instance of {@link LoadBalancerResponse }
     * 
     */
    public LoadBalancerResponse createLoadBalancerResponse() {
        return new LoadBalancerResponse();
    }

    /**
     * Create an instance of {@link DBSecurityGroups }
     * 
     */
    public DBSecurityGroups createDBSecurityGroups() {
        return new DBSecurityGroups();
    }

    /**
     * Create an instance of {@link AppCookieStickinessPoliciesType }
     * 
     */
    public AppCookieStickinessPoliciesType createAppCookieStickinessPoliciesType() {
        return new AppCookieStickinessPoliciesType();
    }

    /**
     * Create an instance of {@link DescribeScalingProcessTypes }
     * 
     */
    public DescribeScalingProcessTypes createDescribeScalingProcessTypes() {
        return new DescribeScalingProcessTypes();
    }

    /**
     * Create an instance of {@link SecurityGroupSetType }
     * 
     */
    public SecurityGroupSetType createSecurityGroupSetType() {
        return new SecurityGroupSetType();
    }

    /**
     * Create an instance of {@link InstanceStateType }
     * 
     */
    public InstanceStateType createInstanceStateType() {
        return new InstanceStateType();
    }

    /**
     * Create an instance of {@link DescribeKeyPairsItemType }
     * 
     */
    public DescribeKeyPairsItemType createDescribeKeyPairsItemType() {
        return new DescribeKeyPairsItemType();
    }

    /**
     * Create an instance of {@link DescribeLoadBalancersResponseType }
     * 
     */
    public DescribeLoadBalancersResponseType createDescribeLoadBalancersResponseType() {
        return new DescribeLoadBalancersResponseType();
    }

    /**
     * Create an instance of {@link InstanceBlockDeviceMappingResponseItemType }
     * 
     */
    public InstanceBlockDeviceMappingResponseItemType createInstanceBlockDeviceMappingResponseItemType() {
        return new InstanceBlockDeviceMappingResponseItemType();
    }

    /**
     * Create an instance of {@link LoadBalancerNamesType }
     * 
     */
    public LoadBalancerNamesType createLoadBalancerNamesType() {
        return new LoadBalancerNamesType();
    }

    /**
     * Create an instance of {@link SuspendedProcessesType }
     * 
     */
    public SuspendedProcessesType createSuspendedProcessesType() {
        return new SuspendedProcessesType();
    }

    /**
     * Create an instance of {@link CreateDBSnapshotDetailsType }
     * 
     */
    public CreateDBSnapshotDetailsType createCreateDBSnapshotDetailsType() {
        return new CreateDBSnapshotDetailsType();
    }

    /**
     * Create an instance of {@link LBCookieStickinessPoliciesType }
     * 
     */
    public LBCookieStickinessPoliciesType createLBCookieStickinessPoliciesType() {
        return new LBCookieStickinessPoliciesType();
    }

    /**
     * Create an instance of {@link IpRangeItemType }
     * 
     */
    public IpRangeItemType createIpRangeItemType() {
        return new IpRangeItemType();
    }

    /**
     * Create an instance of {@link LBCookieStickinessPolicyType }
     * 
     */
    public LBCookieStickinessPolicyType createLBCookieStickinessPolicyType() {
        return new LBCookieStickinessPolicyType();
    }

    /**
     * Create an instance of {@link DescribeSecurityGroupsIdSetItemType }
     * 
     */
    public DescribeSecurityGroupsIdSetItemType createDescribeSecurityGroupsIdSetItemType() {
        return new DescribeSecurityGroupsIdSetItemType();
    }

    /**
     * Create an instance of {@link Dimensions }
     * 
     */
    public Dimensions createDimensions() {
        return new Dimensions();
    }

    /**
     * Create an instance of {@link DeleteKeyPairResponseType }
     * 
     */
    public DeleteKeyPairResponseType createDeleteKeyPairResponseType() {
        return new DeleteKeyPairResponseType();
    }

    /**
     * Create an instance of {@link ProductCodesSetType }
     * 
     */
    public ProductCodesSetType createProductCodesSetType() {
        return new ProductCodesSetType();
    }

    /**
     * Create an instance of {@link CreateAutoScalingGroupType }
     * 
     */
    public CreateAutoScalingGroupType createCreateAutoScalingGroupType() {
        return new CreateAutoScalingGroupType();
    }

    /**
     * Create an instance of {@link DescribeScalingProcessTypesResultType }
     * 
     */
    public DescribeScalingProcessTypesResultType createDescribeScalingProcessTypesResultType() {
        return new DescribeScalingProcessTypesResultType();
    }

    /**
     * Create an instance of {@link AvailabilityZonesType }
     * 
     */
    public AvailabilityZonesType createAvailabilityZonesType() {
        return new AvailabilityZonesType();
    }

    /**
     * Create an instance of {@link ProcessNames }
     * 
     */
    public ProcessNames createProcessNames() {
        return new ProcessNames();
    }

    /**
     * Create an instance of {@link DescribeAutoScalingGroupsResultType }
     * 
     */
    public DescribeAutoScalingGroupsResultType createDescribeAutoScalingGroupsResultType() {
        return new DescribeAutoScalingGroupsResultType();
    }

    /**
     * Create an instance of {@link CreateAppCookieStickinessPolicyType }
     * 
     */
    public CreateAppCookieStickinessPolicyType createCreateAppCookieStickinessPolicyType() {
        return new CreateAppCookieStickinessPolicyType();
    }

    /**
     * Create an instance of {@link UserIdGroupPairSetType }
     * 
     */
    public UserIdGroupPairSetType createUserIdGroupPairSetType() {
        return new UserIdGroupPairSetType();
    }

    /**
     * Create an instance of {@link ResourceList }
     * 
     */
    public ResourceList createResourceList() {
        return new ResourceList();
    }

    /**
     * Create an instance of {@link CreateLaunchConfigurationType }
     * 
     */
    public CreateLaunchConfigurationType createCreateLaunchConfigurationType() {
        return new CreateLaunchConfigurationType();
    }

    /**
     * Create an instance of {@link CreateDBInstanceReadReplicaType }
     * 
     */
    public CreateDBInstanceReadReplicaType createCreateDBInstanceReadReplicaType() {
        return new CreateDBInstanceReadReplicaType();
    }

    /**
     * Create an instance of {@link DescribeSecurityGroupsResponseType }
     * 
     */
    public DescribeSecurityGroupsResponseType createDescribeSecurityGroupsResponseType() {
        return new DescribeSecurityGroupsResponseType();
    }

    /**
     * Create an instance of {@link CreateDBSnapshotType }
     * 
     */
    public CreateDBSnapshotType createCreateDBSnapshotType() {
        return new CreateDBSnapshotType();
    }

    /**
     * Create an instance of {@link DescribeLoadBalancersResultType }
     * 
     */
    public DescribeLoadBalancersResultType createDescribeLoadBalancersResultType() {
        return new DescribeLoadBalancersResultType();
    }

    /**
     * Create an instance of {@link Automata }
     * 
     */
    public Automata createAutomata() {
        return new Automata();
    }

    /**
     * Create an instance of {@link DescribeAutoScalingGroupsType }
     * 
     */
    public DescribeAutoScalingGroupsType createDescribeAutoScalingGroupsType() {
        return new DescribeAutoScalingGroupsType();
    }

    /**
     * Create an instance of {@link DeleteAutoScalingGroupType }
     * 
     */
    public DeleteAutoScalingGroupType createDeleteAutoScalingGroupType() {
        return new DeleteAutoScalingGroupType();
    }

    /**
     * Create an instance of {@link BlockDeviceMappingsType }
     * 
     */
    public BlockDeviceMappingsType createBlockDeviceMappingsType() {
        return new BlockDeviceMappingsType();
    }

    /**
     * Create an instance of {@link FilterSetType }
     * 
     */
    public FilterSetType createFilterSetType() {
        return new FilterSetType();
    }

    /**
     * Create an instance of {@link CreateSecurityGroupType }
     * 
     */
    public CreateSecurityGroupType createCreateSecurityGroupType() {
        return new CreateSecurityGroupType();
    }

    /**
     * Create an instance of {@link DeleteLoadBalancerType }
     * 
     */
    public DeleteLoadBalancerType createDeleteLoadBalancerType() {
        return new DeleteLoadBalancerType();
    }

    /**
     * Create an instance of {@link DescribeDBInstancesType }
     * 
     */
    public DescribeDBInstancesType createDescribeDBInstancesType() {
        return new DescribeDBInstancesType();
    }

    /**
     * Create an instance of {@link EnabledMetricType }
     * 
     */
    public EnabledMetricType createEnabledMetricType() {
        return new EnabledMetricType();
    }

    /**
     * Create an instance of {@link DescribeKeyPairsInfoType }
     * 
     */
    public DescribeKeyPairsInfoType createDescribeKeyPairsInfoType() {
        return new DescribeKeyPairsInfoType();
    }

    /**
     * Create an instance of {@link GroupSetType }
     * 
     */
    public GroupSetType createGroupSetType() {
        return new GroupSetType();
    }

    /**
     * Create an instance of {@link Ec2InstanceResponse }
     * 
     */
    public Ec2InstanceResponse createEc2InstanceResponse() {
        return new Ec2InstanceResponse();
    }

    /**
     * Create an instance of {@link PutScalingPolicyResponse }
     * 
     */
    public PutScalingPolicyResponse createPutScalingPolicyDetailsType() {
        return new PutScalingPolicyResponse();
    }

    /**
     * Create an instance of {@link DeleteSecurityGroupType }
     * 
     */
    public DeleteSecurityGroupType createDeleteSecurityGroupType() {
        return new DeleteSecurityGroupType();
    }

    /**
     * Create an instance of {@link RestoreDBInstanceFromDBSnapshotResultType }
     * 
     */
    public RestoreDBInstanceFromDBSnapshotResultType createRestoreDBInstanceFromDBSnapshotResultType() {
        return new RestoreDBInstanceFromDBSnapshotResultType();
    }

    /**
     * Create an instance of {@link ReservationSetType }
     * 
     */
    public ReservationSetType createReservationSetType() {
        return new ReservationSetType();
    }

    /**
     * Create an instance of {@link CreateDBInstanceResultType }
     * 
     */
    public CreateDBInstanceResultType createCreateDBInstanceResultType() {
        return new CreateDBInstanceResultType();
    }

    /**
     * Create an instance of {@link UpdateAutoScalingGroupType }
     * 
     */
    public UpdateAutoScalingGroupType createUpdateAutoScalingGroupType() {
        return new UpdateAutoScalingGroupType();
    }

    /**
     * Create an instance of {@link PutScalingPolicyType }
     * 
     */
    public PutScalingPolicyType createPutScalingPolicyType() {
        return new PutScalingPolicyType();
    }

    /**
     * Create an instance of {@link InstanceBlockDeviceMappingResponseType }
     * 
     */
    public InstanceBlockDeviceMappingResponseType createInstanceBlockDeviceMappingResponseType() {
        return new InstanceBlockDeviceMappingResponseType();
    }

    /**
     * Create an instance of {@link DescribeInstancesType }
     * 
     */
    public DescribeInstancesType createDescribeInstancesType() {
        return new DescribeInstancesType();
    }

    /**
     * Create an instance of {@link LoadBalancerType }
     * 
     */
    public LoadBalancerType createLoadBalancerType() {
        return new LoadBalancerType();
    }

    /**
     * Create an instance of {@link DescribeLaunchConfigurationsResponseType }
     * 
     */
    public DescribeLaunchConfigurationsResponseType createDescribeLaunchConfigurationsResponseType() {
        return new DescribeLaunchConfigurationsResponseType();
    }

    /**
     * Create an instance of {@link DescribeScalingProcessTypesResponse }
     * 
     */
    public DescribeScalingProcessTypesResponse createDescribeScalingProcessTypesResponse() {
        return new DescribeScalingProcessTypesResponse();
    }

    /**
     * Create an instance of {@link CreateDBInstanceResponse }
     * 
     */
    public CreateDBInstanceResponse createCreateDBInstanceDetailsType() {
        return new CreateDBInstanceResponse();
    }

    /**
     * Create an instance of {@link AuthorizeDBSecurityGroupIngressResponse }
     * 
     */
    public AuthorizeDBSecurityGroupIngressResponse createAuthorizeDBSecurityGroupIngressDetailsType() {
        return new AuthorizeDBSecurityGroupIngressResponse();
    }

    /**
     * Create an instance of {@link ListenerDescriptionsType }
     * 
     */
    public ListenerDescriptionsType createListenerDescriptionsType() {
        return new ListenerDescriptionsType();
    }

    /**
     * Create an instance of {@link EbsInstanceBlockDeviceMappingResponseType }
     * 
     */
    public EbsInstanceBlockDeviceMappingResponseType createEbsInstanceBlockDeviceMappingResponseType() {
        return new EbsInstanceBlockDeviceMappingResponseType();
    }

    /**
     * Create an instance of {@link ProductCodesSetItemType }
     * 
     */
    public ProductCodesSetItemType createProductCodesSetItemType() {
        return new ProductCodesSetItemType();
    }

    /**
     * Create an instance of {@link RestoreDBInstanceFromDBSnapshotType }
     * 
     */
    public RestoreDBInstanceFromDBSnapshotType createRestoreDBInstanceFromDBSnapshotType() {
        return new RestoreDBInstanceFromDBSnapshotType();
    }

    /**
     * Create an instance of {@link DBSecurityGroup }
     * 
     */
    public DBSecurityGroup createDBSecurityGroup() {
        return new DBSecurityGroup();
    }

    /**
     * Create an instance of {@link PutMetricAlarmType }
     * 
     */
    public PutMetricAlarmType createPutMetricAlarmType() {
        return new PutMetricAlarmType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link DeleteLaunchConfigurationType }
     * 
     */
    public DeleteLaunchConfigurationType createDeleteLaunchConfigurationType() {
        return new DeleteLaunchConfigurationType();
    }

    /**
     * Create an instance of {@link CreateDBInstanceReadReplicaResponse }
     * 
     */
    public CreateDBInstanceReadReplicaResponse createCreateDBInstanceReadReplicaDetailsType() {
        return new CreateDBInstanceReadReplicaResponse();
    }

    /**
     * Create an instance of {@link StateReasonType }
     * 
     */
    public StateReasonType createStateReasonType() {
        return new StateReasonType();
    }

    /**
     * Create an instance of {@link EbsType }
     * 
     */
    public EbsType createEbsType() {
        return new EbsType();
    }

    /**
     * Create an instance of {@link GetMetricStatisticsType }
     * 
     */
    public GetMetricStatisticsType createGetMetricStatisticsType() {
        return new GetMetricStatisticsType();
    }

    /**
     * Create an instance of {@link StopInstancesType }
     * 
     */
    public StopInstancesType createStopInstancesType() {
        return new StopInstancesType();
    }

    /**
     * Create an instance of {@link DescribeInstancesResponseType }
     * 
     */
    public DescribeInstancesResponseType createDescribeInstancesResponseType() {
        return new DescribeInstancesResponseType();
    }

    /**
     * Create an instance of {@link DescribeSecurityGroupsSetType }
     * 
     */
    public DescribeSecurityGroupsSetType createDescribeSecurityGroupsSetType() {
        return new DescribeSecurityGroupsSetType();
    }

    /**
     * Create an instance of {@link SuspendProcessesType }
     * 
     */
    public SuspendProcessesType createSuspendProcessesType() {
        return new SuspendProcessesType();
    }

    /**
     * Create an instance of {@link DBInstanceType }
     * 
     */
    public DBInstanceType createDBInstanceType() {
        return new DBInstanceType();
    }

    /**
     * Create an instance of {@link AddSecurityGroupRuleType }
     * 
     */
    public AddSecurityGroupRuleType createAddSecurityGroupRuleType() {
        return new AddSecurityGroupRuleType();
    }

    /**
     * Create an instance of {@link DescribeDBSecurityGroupsResultType }
     * 
     */
    public DescribeDBSecurityGroupsResultType createDescribeDBSecurityGroupsResultType() {
        return new DescribeDBSecurityGroupsResultType();
    }

    /**
     * Create an instance of {@link InstanceType }
     * 
     */
    public InstanceType createInstanceType() {
        return new InstanceType();
    }

    /**
     * Create an instance of {@link EC2SecurityGroupList }
     * 
     */
    public EC2SecurityGroupList createEC2SecurityGroupList() {
        return new EC2SecurityGroupList();
    }

    /**
     * Create an instance of {@link DescribeKeyPairsResponseType }
     * 
     */
    public DescribeKeyPairsResponseType createDescribeKeyPairsResponseType() {
        return new DescribeKeyPairsResponseType();
    }

    /**
     * Create an instance of {@link DeleteSecurityGroupRuleType }
     * 
     */
    public DeleteSecurityGroupRuleType createDeleteSecurityGroupRuleType() {
        return new DeleteSecurityGroupRuleType();
    }

    /**
     * Create an instance of {@link Ec2InstanceType }
     * 
     */
    public Ec2InstanceType createEc2InstanceType() {
        return new Ec2InstanceType();
    }

    /**
     * Create an instance of {@link CreateAppCookieStickinessPolicyResponse }
     * 
     */
    public CreateAppCookieStickinessPolicyResponse createCreateAppCookieStickinessPolicyDetailsType() {
        return new CreateAppCookieStickinessPolicyResponse();
    }

    /**
     * Create an instance of {@link ProcessType }
     * 
     */
    public ProcessType createProcessType() {
        return new ProcessType();
    }

    /**
     * Create an instance of {@link GroupItemType }
     * 
     */
    public GroupItemType createGroupItemType() {
        return new GroupItemType();
    }

    /**
     * Create an instance of {@link DescribeKeyPairsType }
     * 
     */
    public DescribeKeyPairsType createDescribeKeyPairsType() {
        return new DescribeKeyPairsType();
    }

    /**
     * Create an instance of {@link PlacementResponseType }
     * 
     */
    public PlacementResponseType createPlacementResponseType() {
        return new PlacementResponseType();
    }

    /**
     * Create an instance of {@link DeleteDBInstanceResultType }
     * 
     */
    public DeleteDBInstanceResultType createDeleteDBInstanceResultType() {
        return new DeleteDBInstanceResultType();
    }

    /**
     * Create an instance of {@link RunningInstancesSetType }
     * 
     */
    public RunningInstancesSetType createRunningInstancesSetType() {
        return new RunningInstancesSetType();
    }

    /**
     * Create an instance of {@link GetMetricStatisticsDetailsType }
     * 
     */
    public GetMetricStatisticsDetailsType createGetMetricStatisticsDetailsType() {
        return new GetMetricStatisticsDetailsType();
    }

    /**
     * Create an instance of {@link UpdateAutoScalingGroupResponseType }
     * 
     */
    public UpdateAutoScalingGroupResponseType createUpdateAutoScalingGroupResponseType() {
        return new UpdateAutoScalingGroupResponseType();
    }

    /**
     * Create an instance of {@link DescribeDBSecurityGroupsResponseType }
     * 
     */
    public DescribeDBSecurityGroupsResponseType createDescribeDBSecurityGroupsResponseType() {
        return new DescribeDBSecurityGroupsResponseType();
    }

    /**
     * Create an instance of {@link ProcessesType }
     * 
     */
    public ProcessesType createProcessesType() {
        return new ProcessesType();
    }

    /**
     * Create an instance of {@link PutMetricAlarmDetailsType }
     * 
     */
    public PutMetricAlarmDetailsType createPutMetricAlarmDetailsType() {
        return new PutMetricAlarmDetailsType();
    }

    /**
     * Create an instance of {@link AuthorizeDBSecurityGroupIngressType }
     * 
     */
    public AuthorizeDBSecurityGroupIngressType createAuthorizeDBSecurityGroupIngressType() {
        return new AuthorizeDBSecurityGroupIngressType();
    }

    /**
     * Create an instance of {@link DeleteAutoScalingGroupResponseType }
     * 
     */
    public DeleteAutoScalingGroupResponseType createDeleteAutoScalingGroupResponseType() {
        return new DeleteAutoScalingGroupResponseType();
    }

    /**
     * Create an instance of {@link ReservationInfoType }
     * 
     */
    public ReservationInfoType createReservationInfoType() {
        return new ReservationInfoType();
    }

    /**
     * Create an instance of {@link DescribeDBInstancesResponseType }
     * 
     */
    public DescribeDBInstancesResponseType createDescribeDBInstancesResponseType() {
        return new DescribeDBInstancesResponseType();
    }

    /**
     * Create an instance of {@link DBSnapshotType }
     * 
     */
    public DBSnapshotType createDBSnapshotType() {
        return new DBSnapshotType();
    }

    /**
     * Create an instance of {@link DescribeLoadBalancersType }
     * 
     */
    public DescribeLoadBalancersType createDescribeLoadBalancersType() {
        return new DescribeLoadBalancersType();
    }

    /**
     * Create an instance of {@link Statistics }
     * 
     */
    public Statistics createStatistics() {
        return new Statistics();
    }

    /**
     * Create an instance of {@link DescribeSecurityGroupsSetItemType }
     * 
     */
    public DescribeSecurityGroupsSetItemType createDescribeSecurityGroupsSetItemType() {
        return new DescribeSecurityGroupsSetItemType();
    }

    /**
     * Create an instance of {@link TerminateInstancesResponseType }
     * 
     */
    public TerminateInstancesResponseType createTerminateInstancesResponseType() {
        return new TerminateInstancesResponseType();
    }

    /**
     * Create an instance of {@link IPRangeList }
     * 
     */
    public IPRangeList createIPRangeList() {
        return new IPRangeList();
    }

    /**
     * Create an instance of {@link DeleteSecurityGroupRuleDetailsType }
     * 
     */
    public DeleteSecurityGroupRuleDetailsType createDeleteSecurityGroupRuleDetailsType() {
        return new DeleteSecurityGroupRuleDetailsType();
    }

    /**
     * Create an instance of {@link PoliciesType }
     * 
     */
    public PoliciesType createPoliciesType() {
        return new PoliciesType();
    }

    /**
     * Create an instance of {@link InstancesType }
     * 
     */
    public InstancesType createInstancesType() {
        return new InstancesType();
    }

    /**
     * Create an instance of {@link DeleteDBInstanceType }
     * 
     */
    public DeleteDBInstanceType createDeleteDBInstanceType() {
        return new DeleteDBInstanceType();
    }

    /**
     * Create an instance of {@link MetricGranularityType }
     * 
     */
    public MetricGranularityType createMetricGranularityType() {
        return new MetricGranularityType();
    }

    /**
     * Create an instance of {@link InstanceMonitoringStateType }
     * 
     */
    public InstanceMonitoringStateType createInstanceMonitoringStateType() {
        return new InstanceMonitoringStateType();
    }

    /**
     * Create an instance of {@link Resources }
     * 
     */
    public Resources createResources() {
        return new Resources();
    }

    /**
     * Create an instance of {@link StopInstancesResponseType }
     * 
     */
    public StopInstancesResponseType createStopInstancesResponseType() {
        return new StopInstancesResponseType();
    }

    /**
     * Create an instance of {@link DBSecurityGroupNameList }
     * 
     */
    public DBSecurityGroupNameList createDBSecurityGroupNameList() {
        return new DBSecurityGroupNameList();
    }

    /**
     * Create an instance of {@link IpRangeSetType }
     * 
     */
    public IpRangeSetType createIpRangeSetType() {
        return new IpRangeSetType();
    }

    /**
     * Create an instance of {@link StartInstancesType }
     * 
     */
    public StartInstancesType createStartInstancesType() {
        return new StartInstancesType();
    }

    /**
     * Create an instance of {@link DescribeInstancesItemType }
     * 
     */
    public DescribeInstancesItemType createDescribeInstancesItemType() {
        return new DescribeInstancesItemType();
    }

    /**
     * Create an instance of {@link FilterType }
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link CreateDBSecurityGroupType }
     * 
     */
    public CreateDBSecurityGroupType createCreateDBSecurityGroupType() {
        return new CreateDBSecurityGroupType();
    }

    /**
     * Create an instance of {@link StartInstancesResponseType }
     * 
     */
    public StartInstancesResponseType createStartInstancesResponseType() {
        return new StartInstancesResponseType();
    }

    /**
     * Create an instance of {@link PolicyNamesType }
     * 
     */
    public PolicyNamesType createPolicyNamesType() {
        return new PolicyNamesType();
    }

    /**
     * Create an instance of {@link LaunchConfigurationType }
     * 
     */
    public LaunchConfigurationType createLaunchConfigurationType() {
        return new LaunchConfigurationType();
    }

    /**
     * Create an instance of {@link DeleteKeyPairType }
     * 
     */
    public DeleteKeyPairType createDeleteKeyPairType() {
        return new DeleteKeyPairType();
    }

    /**
     * Create an instance of {@link DBInstanceListType }
     * 
     */
    public DBInstanceListType createDBInstanceListType() {
        return new DBInstanceListType();
    }

    /**
     * Create an instance of {@link ResponseMetadataType }
     * 
     */
    public ResponseMetadataType createResponseMetadataType() {
        return new ResponseMetadataType();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link Outputs }
     * 
     */
    public Outputs createOutputs() {
        return new Outputs();
    }

    /**
     * Create an instance of {@link TerminateInstancesType }
     * 
     */
    public TerminateInstancesType createTerminateInstancesType() {
        return new TerminateInstancesType();
    }

    /**
     * Create an instance of {@link LaunchConfigurationNamesType }
     * 
     */
    public LaunchConfigurationNamesType createLaunchConfigurationNamesType() {
        return new LaunchConfigurationNamesType();
    }

    /**
     * Create an instance of {@link UserIdGroupPairType }
     * 
     */
    public UserIdGroupPairType createUserIdGroupPairType() {
        return new UserIdGroupPairType();
    }

    /**
     * Create an instance of {@link DescribeKeyPairsResponseInfoType }
     * 
     */
    public DescribeKeyPairsResponseInfoType createDescribeKeyPairsResponseInfoType() {
        return new DescribeKeyPairsResponseInfoType();
    }

    /**
     * Create an instance of {@link DescribeKeyPairsResponseItemType }
     * 
     */
    public DescribeKeyPairsResponseItemType createDescribeKeyPairsResponseItemType() {
        return new DescribeKeyPairsResponseItemType();
    }

    /**
     * Create an instance of {@link CreateKeyPairType }
     * 
     */
    public CreateKeyPairType createCreateKeyPairType() {
        return new CreateKeyPairType();
    }

    /**
     * Create an instance of {@link InstanceStateChangeType }
     * 
     */
    public InstanceStateChangeType createInstanceStateChangeType() {
        return new InstanceStateChangeType();
    }

    /**
     * Create an instance of {@link CreateSecurityGroupResponse }
     * 
     */
    public CreateSecurityGroupResponse createCreateSecurityGroupResponse() {
        return new CreateSecurityGroupResponse();
    }

    /**
     * Create an instance of {@link CreateKeyPairResponse }
     * 
     */
    public CreateKeyPairResponse createCreateKeyPairResponse() {
        return new CreateKeyPairResponse();
    }

    /**
     * Create an instance of {@link BlockDeviceMappingType }
     * 
     */
    public BlockDeviceMappingType createBlockDeviceMappingType() {
        return new BlockDeviceMappingType();
    }

    /**
     * Create an instance of {@link DescribeDBInstancesResultType }
     * 
     */
    public DescribeDBInstancesResultType createDescribeDBInstancesResultType() {
        return new DescribeDBInstancesResultType();
    }

    /**
     * Create an instance of {@link AutoScalingGroupNamesType }
     * 
     */
    public AutoScalingGroupNamesType createAutoScalingGroupNamesType() {
        return new AutoScalingGroupNamesType();
    }

    /**
     * Create an instance of {@link SuspendedProcessType }
     * 
     */
    public SuspendedProcessType createSuspendedProcessType() {
        return new SuspendedProcessType();
    }

    /**
     * Create an instance of {@link SecurityGroupItemType }
     * 
     */
    public SecurityGroupItemType createSecurityGroupItemType() {
        return new SecurityGroupItemType();
    }

    /**
     * Create an instance of {@link InstanceIdType }
     * 
     */
    public InstanceIdType createInstanceIdType() {
        return new InstanceIdType();
    }

    /**
     * Create an instance of {@link DeleteLaunchConfigurationResponseType }
     * 
     */
    public DeleteLaunchConfigurationResponseType createDeleteLaunchConfigurationResponseType() {
        return new DeleteLaunchConfigurationResponseType();
    }

    /**
     * Create an instance of {@link DescribeSecurityGroupsIdSetType }
     * 
     */
    public DescribeSecurityGroupsIdSetType createDescribeSecurityGroupsIdSetType() {
        return new DescribeSecurityGroupsIdSetType();
    }

    /**
     * Create an instance of {@link DeleteLoadBalancerResponseType }
     * 
     */
    public DeleteLoadBalancerResponseType createDeleteLoadBalancerResponseType() {
        return new DeleteLoadBalancerResponseType();
    }

    /**
     * Create an instance of {@link CreateAutoScalingGroupResponse }
     * 
     */
    public CreateAutoScalingGroupResponse createCreateAutoScalingGroupDetailsType() {
        return new CreateAutoScalingGroupResponse();
    }

    /**
     * Create an instance of {@link LaunchConfigurationsType }
     * 
     */
    public LaunchConfigurationsType createLaunchConfigurationsType() {
        return new LaunchConfigurationsType();
    }

    /**
     * Create an instance of {@link ResourceTagSetType }
     * 
     */
    public ResourceTagSetType createResourceTagSetType() {
        return new ResourceTagSetType();
    }

    /**
     * Create an instance of {@link PendingModifiedValuesType }
     * 
     */
    public PendingModifiedValuesType createPendingModifiedValuesType() {
        return new PendingModifiedValuesType();
    }

    /**
     * Create an instance of {@link DBParameterGroupStatusListType }
     * 
     */
    public DBParameterGroupStatusListType createDBParameterGroupStatusListType() {
        return new DBParameterGroupStatusListType();
    }

    /**
     * Create an instance of {@link DescribeLaunchConfigurationsResultType }
     * 
     */
    public DescribeLaunchConfigurationsResultType createDescribeLaunchConfigurationsResultType() {
        return new DescribeLaunchConfigurationsResultType();
    }

    /**
     * Create an instance of {@link CreateLaunchConfigurationResponse }
     * 
     */
    public CreateLaunchConfigurationResponse createCreateLaunchConfigurationDetailsType() {
        return new CreateLaunchConfigurationResponse();
    }

    /**
     * Create an instance of {@link ResourceTagSetItemType }
     * 
     */
    public ResourceTagSetItemType createResourceTagSetItemType() {
        return new ResourceTagSetItemType();
    }

    /**
     * Create an instance of {@link AutoScalingGroupType }
     * 
     */
    public AutoScalingGroupType createAutoScalingGroupType() {
        return new AutoScalingGroupType();
    }

    /**
     * Create an instance of {@link DescribeAutoScalingGroupsResponseType }
     * 
     */
    public DescribeAutoScalingGroupsResponseType createDescribeAutoScalingGroupsResponseType() {
        return new DescribeAutoScalingGroupsResponseType();
    }

    /**
     * Create an instance of {@link DeleteLoadBalancerResultType }
     * 
     */
    public DeleteLoadBalancerResultType createDeleteLoadBalancerResultType() {
        return new DeleteLoadBalancerResultType();
    }

    /**
     * Create an instance of {@link DescribeDBSecurityGroupsType }
     * 
     */
    public DescribeDBSecurityGroupsType createDescribeDBSecurityGroupsType() {
        return new DescribeDBSecurityGroupsType();
    }

    /**
     * Create an instance of {@link InstanceStateChangeSetType }
     * 
     */
    public InstanceStateChangeSetType createInstanceStateChangeSetType() {
        return new InstanceStateChangeSetType();
    }

    /**
     * Create an instance of {@link LoadBalancerDescriptionsType }
     * 
     */
    public LoadBalancerDescriptionsType createLoadBalancerDescriptionsType() {
        return new LoadBalancerDescriptionsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Automata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Automata")
    public JAXBElement<Automata> createAutomata(Automata value) {
        return new JAXBElement<Automata>(_Automata_QNAME, Automata.class, null, value);
    }

}
