//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.28 at 08:08:58 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutputsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutputsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InstanceDetails" type="{}InstanceDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateKeyPairDetails" type="{}CreateKeyPairDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LoadBalancerDetails" type="{}LoadBalancerDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateAppCookieStickinessPolicyDetails" type="{}CreateAppCookieStickinessPolicyDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateLBCookieStickinessPolicyDetails" type="{}CreateLBCookieStickinessPolicyDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateLaunchConfigurationDetails" type="{}CreateLaunchConfigurationDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateCreateAutoScalingGroupGroupDetails" type="{}CreateAutoScalingGroupDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AddSecurityGroupRuleDetails" type="{}AddSecurityGroupRuleDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteSecurityGroupRuleDetails" type="{}DeleteSecurityGroupRuleDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateSecurityGroupDetails" type="{}CreateSecurityGroupDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AuthorizeDBSecurityGroupIngressDetails" type="{}AuthorizeDBSecurityGroupIngressDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateDBSecurityGroupDetails" type="{}CreateDBSecurityGroupDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LaunchRDSInstanceDetails" type="{}CreateDBInstanceDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateDBInstanceReadReplicaDetails" type="{}CreateDBInstanceReadReplicaDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateDBSnapshotDetails" type="{}CreateDBSnapshotDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PutScalingPolicyDetails" type="{}PutScalingPolicyDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PutMetricAlarmDetails" type="{}PutMetricAlarmDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GetMetricStatisticsDetails" type="{}GetMetricStatisticsDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UpdateAutoScalingGroupResponse" type="{}UpdateAutoScalingGroupResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteAutoScalingGroupResponse" type="{}DeleteAutoScalingGroupResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteLaunchConfigurationResponse" type="{}DeleteLaunchConfigurationResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteLoadBalancerResponse" type="{}DeleteLoadBalancerResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TerminateInstancesResponse" type="{}TerminateInstancesResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteDBInstanceResponse" type="{}DeleteDBInstanceResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteKeyPairResponse" type="{}DeleteKeyPairResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteSecurityGroupResponse" type="{}DeleteSecurityGroupResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteDBSecurityGroupResponse" type="{}DeleteDBSecurityGroupResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StopInstancesResponse" type="{}StopInstancesResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SuspendProcessesResponse" type="{}SuspendProcessesResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StartInstancesResponse" type="{}StartInstancesResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ResumeProcessesResponse" type="{}ResumeProcessesResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RestoreDBInstanceFromDBSnapshotResponse" type="{}RestoreDBInstanceFromDBSnapshotResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeInstancesResponse" type="{}DescribeInstancesResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeKeyPairsResponse" type="{}DescribeKeyPairsResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeSecurityGroupsResponse" type="{}DescribeSecurityGroupsResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeInstances" type="{}DescribeInstancesResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeLoadBalancersResponse" type="{}DescribeLoadBalancersResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeLaunchConfigurationsResponse" type="{}DescribeLaunchConfigurationsResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeScalingProcessResponse" type="{}DescribeScalingProcessTypesResponse" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeAutoScalingGroupsResponse" type="{}DescribeAutoScalingGroupsResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeDBSecurityGroupsResponse" type="{}DescribeDBSecurityGroupsResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeDBInstancesResponse" type="{}DescribeDBInstancesResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutputsType", propOrder = {
    "instanceDetails",
    "createKeyPairDetails",
    "loadBalancerDetails",
    "createAppCookieStickinessPolicyDetails",
    "createLBCookieStickinessPolicyDetails",
    "createLaunchConfigurationDetails",
    "createAutoScalingGroupDetails",
    "addSecurityGroupRuleDetails",
    "deleteSecurityGroupRuleDetails",
    "createSecurityGroupDetails",
    "authorizeDBSecurityGroupIngressDetails",
    "createDBSecurityGroupDetails",
    "launchRDSInstanceDetails",
    "createDBInstanceReadReplicaDetails",
    "createDBSnapshotDetails",
    "putScalingPolicyDetails",
    "putMetricAlarmDetails",
    "getMetricStatisticsDetails",
    "updateAutoScalingGroupResponse",
    "deleteAutoScalingGroupResponse",
    "deleteLaunchConfigurationResponse",
    "deleteLoadBalancerResponse",
    "terminateInstancesResponse",
    "deleteDBInstanceResponse",
    "deleteKeyPairResponse",
    "deleteSecurityGroupResponse",
    "deleteDBSecurityGroupResponse",
    "stopInstancesResponse",
    "suspendProcessesResponse",
    "startInstancesResponse",
    "resumeProcessesResponse",
    "restoreDBInstanceFromDBSnapshotResponse",
    "describeInstancesResponse",
    "describeKeyPairsResponse",
    "describeSecurityGroupsResponse",
    "describeInstances",
    "describeLoadBalancersResponse",
    "describeLaunchConfigurationsResponse",
    "describeScalingProcessResponse",
    "describeAutoScalingGroupsResponse",
    "describeDBSecurityGroupsResponse",
    "describeDBInstancesResponse"
})
public class Outputs {

    @XmlElement(name = "InstanceDetails")
    protected List<Ec2InstanceResponse> instanceDetails;
    @XmlElement(name = "CreateKeyPairDetails")
    protected List<CreateKeyPairResponse> createKeyPairDetails;
    @XmlElement(name = "LoadBalancerDetails")
    protected List<LoadBalancerResponse> loadBalancerDetails;
    @XmlElement(name = "CreateAppCookieStickinessPolicyDetails")
    protected List<CreateAppCookieStickinessPolicyResponse> createAppCookieStickinessPolicyDetails;
    @XmlElement(name = "CreateLBCookieStickinessPolicyDetails")
    protected List<CreateLBCookieStickinessPolicyResponse> createLBCookieStickinessPolicyDetails;
    @XmlElement(name = "CreateLaunchConfigurationDetails")
    protected List<CreateLaunchConfigurationResponse> createLaunchConfigurationDetails;
    @XmlElement(name = "CreateCreateAutoScalingGroupGroupDetails")
    protected List<CreateAutoScalingGroupResponse> createAutoScalingGroupDetails;
    @XmlElement(name = "AddSecurityGroupRuleDetails")
    protected List<AddSecurityGroupRuleResponse> addSecurityGroupRuleDetails;
    @XmlElement(name = "DeleteSecurityGroupRuleDetails")
    protected List<DeleteSecurityGroupRuleDetailsType> deleteSecurityGroupRuleDetails;
    @XmlElement(name = "CreateSecurityGroupDetails")
    protected List<CreateSecurityGroupResponse> createSecurityGroupDetails;
    @XmlElement(name = "AuthorizeDBSecurityGroupIngressDetails")
    protected List<AuthorizeDBSecurityGroupIngressResponse> authorizeDBSecurityGroupIngressDetails;
    @XmlElement(name = "CreateDBSecurityGroupDetails")
    protected List<CreateDBSecurityGroupResponse> createDBSecurityGroupDetails;
    @XmlElement(name = "LaunchRDSInstanceDetails")
    protected List<CreateDBInstanceResponse> launchRDSInstanceDetails;
    @XmlElement(name = "CreateDBInstanceReadReplicaDetails")
    protected List<CreateDBInstanceReadReplicaResponse> createDBInstanceReadReplicaDetails;
    @XmlElement(name = "CreateDBSnapshotDetails")
    protected List<CreateDBSnapshotDetailsType> createDBSnapshotDetails;
    @XmlElement(name = "PutScalingPolicyDetails")
    protected List<PutScalingPolicyResponse> putScalingPolicyDetails;
    @XmlElement(name = "PutMetricAlarmDetails")
    protected List<PutMetricAlarmDetailsType> putMetricAlarmDetails;
    @XmlElement(name = "GetMetricStatisticsDetails")
    protected List<GetMetricStatisticsDetailsType> getMetricStatisticsDetails;
    @XmlElement(name = "UpdateAutoScalingGroupResponse")
    protected List<UpdateAutoScalingGroupResponseType> updateAutoScalingGroupResponse;
    @XmlElement(name = "DeleteAutoScalingGroupResponse")
    protected List<DeleteAutoScalingGroupResponseType> deleteAutoScalingGroupResponse;
    @XmlElement(name = "DeleteLaunchConfigurationResponse")
    protected List<DeleteLaunchConfigurationResponseType> deleteLaunchConfigurationResponse;
    @XmlElement(name = "DeleteLoadBalancerResponse")
    protected List<DeleteLoadBalancerResponseType> deleteLoadBalancerResponse;
    @XmlElement(name = "TerminateInstancesResponse")
    protected List<TerminateInstancesResponseType> terminateInstancesResponse;
    @XmlElement(name = "DeleteDBInstanceResponse")
    protected List<DeleteDBInstanceResponseType> deleteDBInstanceResponse;
    @XmlElement(name = "DeleteKeyPairResponse")
    protected List<DeleteKeyPairResponseType> deleteKeyPairResponse;
    @XmlElement(name = "DeleteSecurityGroupResponse")
    protected List<DeleteSecurityGroupResponseType> deleteSecurityGroupResponse;
    @XmlElement(name = "DeleteDBSecurityGroupResponse")
    protected List<DeleteDBSecurityGroupResponseType> deleteDBSecurityGroupResponse;
    @XmlElement(name = "StopInstancesResponse")
    protected List<StopInstancesResponseType> stopInstancesResponse;
    @XmlElement(name = "SuspendProcessesResponse")
    protected List<SuspendProcessesResponseType> suspendProcessesResponse;
    @XmlElement(name = "StartInstancesResponse")
    protected List<StartInstancesResponseType> startInstancesResponse;
    @XmlElement(name = "ResumeProcessesResponse")
    protected List<ResumeProcessesResponseType> resumeProcessesResponse;
    @XmlElement(name = "RestoreDBInstanceFromDBSnapshotResponse")
    protected List<RestoreDBInstanceFromDBSnapshotResponseType> restoreDBInstanceFromDBSnapshotResponse;
    @XmlElement(name = "DescribeInstancesResponse")
    protected List<DescribeInstancesResponseType> describeInstancesResponse;
    @XmlElement(name = "DescribeKeyPairsResponse")
    protected List<DescribeKeyPairsResponseType> describeKeyPairsResponse;
    @XmlElement(name = "DescribeSecurityGroupsResponse")
    protected List<DescribeSecurityGroupsResponseType> describeSecurityGroupsResponse;
    @XmlElement(name = "DescribeInstances")
    protected List<DescribeInstancesResponseType> describeInstances;
    @XmlElement(name = "DescribeLoadBalancersResponse")
    protected List<DescribeLoadBalancersResponseType> describeLoadBalancersResponse;
    @XmlElement(name = "DescribeLaunchConfigurationsResponse")
    protected List<DescribeLaunchConfigurationsResponseType> describeLaunchConfigurationsResponse;
    @XmlElement(name = "DescribeScalingProcessResponse")
    protected List<DescribeScalingProcessTypesResponse> describeScalingProcessResponse;
    @XmlElement(name = "DescribeAutoScalingGroupsResponse")
    protected List<DescribeAutoScalingGroupsResponseType> describeAutoScalingGroupsResponse;
    @XmlElement(name = "DescribeDBSecurityGroupsResponse")
    protected List<DescribeDBSecurityGroupsResponseType> describeDBSecurityGroupsResponse;
    @XmlElement(name = "DescribeDBInstancesResponse")
    protected List<DescribeDBInstancesResponseType> describeDBInstancesResponse;

    /**
     * Gets the value of the instanceDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instanceDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstanceDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ec2InstanceResponse }
     * 
     * 
     */
    public List<Ec2InstanceResponse> getInstanceDetails() {
        if (instanceDetails == null) {
            instanceDetails = new ArrayList<Ec2InstanceResponse>();
        }
        return this.instanceDetails;
    }

    /**
     * Gets the value of the createKeyPairDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createKeyPairDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateKeyPairDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateKeyPairResponse }
     * 
     * 
     */
    public List<CreateKeyPairResponse> getCreateKeyPairDetails() {
        if (createKeyPairDetails == null) {
            createKeyPairDetails = new ArrayList<CreateKeyPairResponse>();
        }
        return this.createKeyPairDetails;
    }

    /**
     * Gets the value of the loadBalancerDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loadBalancerDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoadBalancerDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoadBalancerResponse }
     * 
     * 
     */
    public List<LoadBalancerResponse> getLoadBalancerDetails() {
        if (loadBalancerDetails == null) {
            loadBalancerDetails = new ArrayList<LoadBalancerResponse>();
        }
        return this.loadBalancerDetails;
    }

    /**
     * Gets the value of the createAppCookieStickinessPolicyDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createAppCookieStickinessPolicyDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateAppCookieStickinessPolicyDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateAppCookieStickinessPolicyResponse }
     * 
     * 
     */
    public List<CreateAppCookieStickinessPolicyResponse> getCreateAppCookieStickinessPolicyDetails() {
        if (createAppCookieStickinessPolicyDetails == null) {
            createAppCookieStickinessPolicyDetails = new ArrayList<CreateAppCookieStickinessPolicyResponse>();
        }
        return this.createAppCookieStickinessPolicyDetails;
    }

    /**
     * Gets the value of the createLBCookieStickinessPolicyDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createLBCookieStickinessPolicyDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateLBCookieStickinessPolicyDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateLBCookieStickinessPolicyResponse }
     * 
     * 
     */
    public List<CreateLBCookieStickinessPolicyResponse> getCreateLBCookieStickinessPolicyDetails() {
        if (createLBCookieStickinessPolicyDetails == null) {
            createLBCookieStickinessPolicyDetails = new ArrayList<CreateLBCookieStickinessPolicyResponse>();
        }
        return this.createLBCookieStickinessPolicyDetails;
    }

    /**
     * Gets the value of the createLaunchConfigurationDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createLaunchConfigurationDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateLaunchConfigurationDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateLaunchConfigurationResponse }
     * 
     * 
     */
    public List<CreateLaunchConfigurationResponse> getCreateLaunchConfigurationDetails() {
        if (createLaunchConfigurationDetails == null) {
            createLaunchConfigurationDetails = new ArrayList<CreateLaunchConfigurationResponse>();
        }
        return this.createLaunchConfigurationDetails;
    }

    /**
     * Gets the value of the createCreateAutoScalingGroupGroupDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createCreateAutoScalingGroupGroupDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateCreateAutoScalingGroupGroupDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateAutoScalingGroupResponse }
     * 
     * 
     */
    public List<CreateAutoScalingGroupResponse> getCreateCreateAutoScalingGroupGroupDetails() {
        if (createAutoScalingGroupDetails == null) {
            createAutoScalingGroupDetails = new ArrayList<CreateAutoScalingGroupResponse>();
        }
        return this.createAutoScalingGroupDetails;
    }

    /**
     * Gets the value of the addSecurityGroupRuleDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addSecurityGroupRuleDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddSecurityGroupRuleDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddSecurityGroupRuleResponse }
     * 
     * 
     */
    public List<AddSecurityGroupRuleResponse> getAddSecurityGroupRuleDetails() {
        if (addSecurityGroupRuleDetails == null) {
            addSecurityGroupRuleDetails = new ArrayList<AddSecurityGroupRuleResponse>();
        }
        return this.addSecurityGroupRuleDetails;
    }

    /**
     * Gets the value of the deleteSecurityGroupRuleDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteSecurityGroupRuleDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteSecurityGroupRuleDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteSecurityGroupRuleDetailsType }
     * 
     * 
     */
    public List<DeleteSecurityGroupRuleDetailsType> getDeleteSecurityGroupRuleDetails() {
        if (deleteSecurityGroupRuleDetails == null) {
            deleteSecurityGroupRuleDetails = new ArrayList<DeleteSecurityGroupRuleDetailsType>();
        }
        return this.deleteSecurityGroupRuleDetails;
    }

    /**
     * Gets the value of the createSecurityGroupDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createSecurityGroupDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateSecurityGroupDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateSecurityGroupResponse }
     * 
     * 
     */
    public List<CreateSecurityGroupResponse> getCreateSecurityGroupDetails() {
        if (createSecurityGroupDetails == null) {
            createSecurityGroupDetails = new ArrayList<CreateSecurityGroupResponse>();
        }
        return this.createSecurityGroupDetails;
    }

    /**
     * Gets the value of the authorizeDBSecurityGroupIngressDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorizeDBSecurityGroupIngressDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorizeDBSecurityGroupIngressDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorizeDBSecurityGroupIngressResponse }
     * 
     * 
     */
    public List<AuthorizeDBSecurityGroupIngressResponse> getAuthorizeDBSecurityGroupIngressDetails() {
        if (authorizeDBSecurityGroupIngressDetails == null) {
            authorizeDBSecurityGroupIngressDetails = new ArrayList<AuthorizeDBSecurityGroupIngressResponse>();
        }
        return this.authorizeDBSecurityGroupIngressDetails;
    }

    /**
     * Gets the value of the createDBSecurityGroupDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createDBSecurityGroupDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateDBSecurityGroupDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateDBSecurityGroupResponse }
     * 
     * 
     */
    public List<CreateDBSecurityGroupResponse> getCreateDBSecurityGroupDetails() {
        if (createDBSecurityGroupDetails == null) {
            createDBSecurityGroupDetails = new ArrayList<CreateDBSecurityGroupResponse>();
        }
        return this.createDBSecurityGroupDetails;
    }

    /**
     * Gets the value of the launchRDSInstanceDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the launchRDSInstanceDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLaunchRDSInstanceDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateDBInstanceResponse }
     * 
     * 
     */
    public List<CreateDBInstanceResponse> getLaunchRDSInstanceDetails() {
        if (launchRDSInstanceDetails == null) {
            launchRDSInstanceDetails = new ArrayList<CreateDBInstanceResponse>();
        }
        return this.launchRDSInstanceDetails;
    }

    /**
     * Gets the value of the createDBInstanceReadReplicaDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createDBInstanceReadReplicaDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateDBInstanceReadReplicaDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateDBInstanceReadReplicaResponse }
     * 
     * 
     */
    public List<CreateDBInstanceReadReplicaResponse> getCreateDBInstanceReadReplicaDetails() {
        if (createDBInstanceReadReplicaDetails == null) {
            createDBInstanceReadReplicaDetails = new ArrayList<CreateDBInstanceReadReplicaResponse>();
        }
        return this.createDBInstanceReadReplicaDetails;
    }

    /**
     * Gets the value of the createDBSnapshotDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createDBSnapshotDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateDBSnapshotDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateDBSnapshotDetailsType }
     * 
     * 
     */
    public List<CreateDBSnapshotDetailsType> getCreateDBSnapshotDetails() {
        if (createDBSnapshotDetails == null) {
            createDBSnapshotDetails = new ArrayList<CreateDBSnapshotDetailsType>();
        }
        return this.createDBSnapshotDetails;
    }

    /**
     * Gets the value of the putScalingPolicyDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the putScalingPolicyDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPutScalingPolicyDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PutScalingPolicyResponse }
     * 
     * 
     */
    public List<PutScalingPolicyResponse> getPutScalingPolicyDetails() {
        if (putScalingPolicyDetails == null) {
            putScalingPolicyDetails = new ArrayList<PutScalingPolicyResponse>();
        }
        return this.putScalingPolicyDetails;
    }

    /**
     * Gets the value of the putMetricAlarmDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the putMetricAlarmDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPutMetricAlarmDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PutMetricAlarmDetailsType }
     * 
     * 
     */
    public List<PutMetricAlarmDetailsType> getPutMetricAlarmDetails() {
        if (putMetricAlarmDetails == null) {
            putMetricAlarmDetails = new ArrayList<PutMetricAlarmDetailsType>();
        }
        return this.putMetricAlarmDetails;
    }

    /**
     * Gets the value of the getMetricStatisticsDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the getMetricStatisticsDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGetMetricStatisticsDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetMetricStatisticsDetailsType }
     * 
     * 
     */
    public List<GetMetricStatisticsDetailsType> getGetMetricStatisticsDetails() {
        if (getMetricStatisticsDetails == null) {
            getMetricStatisticsDetails = new ArrayList<GetMetricStatisticsDetailsType>();
        }
        return this.getMetricStatisticsDetails;
    }

/**
     * Gets the value of the updateAutoScalingGroupResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the updateAutoScalingGroupResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpdateAutoScalingGroupResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateAutoScalingGroupResponseType }
     * 
     * 
     */
    public List<UpdateAutoScalingGroupResponseType> getUpdateAutoScalingGroupResponse() {
        if (updateAutoScalingGroupResponse == null) {
            updateAutoScalingGroupResponse = new ArrayList<UpdateAutoScalingGroupResponseType>();
        }
        return this.updateAutoScalingGroupResponse;
    }

    /**
     * Gets the value of the deleteAutoScalingGroupResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteAutoScalingGroupResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteAutoScalingGroupResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteAutoScalingGroupResponseType }
     * 
     * 
     */
    public List<DeleteAutoScalingGroupResponseType> getDeleteAutoScalingGroupResponse() {
        if (deleteAutoScalingGroupResponse == null) {
            deleteAutoScalingGroupResponse = new ArrayList<DeleteAutoScalingGroupResponseType>();
        }
        return this.deleteAutoScalingGroupResponse;
    }

    /**
     * Gets the value of the deleteLaunchConfigurationResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteLaunchConfigurationResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteLaunchConfigurationResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteLaunchConfigurationResponseType }
     * 
     * 
     */
    public List<DeleteLaunchConfigurationResponseType> getDeleteLaunchConfigurationResponse() {
        if (deleteLaunchConfigurationResponse == null) {
            deleteLaunchConfigurationResponse = new ArrayList<DeleteLaunchConfigurationResponseType>();
        }
        return this.deleteLaunchConfigurationResponse;
    }

    /**
     * Gets the value of the deleteLoadBalancerResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteLoadBalancerResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteLoadBalancerResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteLoadBalancerResponseType }
     * 
     * 
     */
    public List<DeleteLoadBalancerResponseType> getDeleteLoadBalancerResponse() {
        if (deleteLoadBalancerResponse == null) {
            deleteLoadBalancerResponse = new ArrayList<DeleteLoadBalancerResponseType>();
        }
        return this.deleteLoadBalancerResponse;
    }

    /**
     * Gets the value of the terminateInstancesResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the terminateInstancesResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerminateInstancesResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TerminateInstancesResponseType }
     * 
     * 
     */
    public List<TerminateInstancesResponseType> getTerminateInstancesResponse() {
        if (terminateInstancesResponse == null) {
            terminateInstancesResponse = new ArrayList<TerminateInstancesResponseType>();
        }
        return this.terminateInstancesResponse;
    }

    /**
     * Gets the value of the deleteDBInstanceResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteDBInstanceResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteDBInstanceResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteDBInstanceResponseType }
     * 
     * 
     */
    public List<DeleteDBInstanceResponseType> getDeleteDBInstanceResponse() {
        if (deleteDBInstanceResponse == null) {
            deleteDBInstanceResponse = new ArrayList<DeleteDBInstanceResponseType>();
        }
        return this.deleteDBInstanceResponse;
    }

    /**
     * Gets the value of the deleteKeyPairResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteKeyPairResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteKeyPairResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteKeyPairResponseType }
     * 
     * 
     */
    public List<DeleteKeyPairResponseType> getDeleteKeyPairResponse() {
        if (deleteKeyPairResponse == null) {
            deleteKeyPairResponse = new ArrayList<DeleteKeyPairResponseType>();
        }
        return this.deleteKeyPairResponse;
    }

    /**
     * Gets the value of the deleteSecurityGroupResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteSecurityGroupResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteSecurityGroupResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteSecurityGroupResponseType }
     * 
     * 
     */
    public List<DeleteSecurityGroupResponseType> getDeleteSecurityGroupResponse() {
        if (deleteSecurityGroupResponse == null) {
            deleteSecurityGroupResponse = new ArrayList<DeleteSecurityGroupResponseType>();
        }
        return this.deleteSecurityGroupResponse;
    }

    /**
     * Gets the value of the deleteDBSecurityGroupResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteDBSecurityGroupResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteDBSecurityGroupResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteDBSecurityGroupResponseType }
     * 
     * 
     */
    public List<DeleteDBSecurityGroupResponseType> getDeleteDBSecurityGroupResponse() {
        if (deleteDBSecurityGroupResponse == null) {
            deleteDBSecurityGroupResponse = new ArrayList<DeleteDBSecurityGroupResponseType>();
        }
        return this.deleteDBSecurityGroupResponse;
    }

    /**
     * Gets the value of the stopInstancesResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stopInstancesResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStopInstancesResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StopInstancesResponseType }
     * 
     * 
     */
    public List<StopInstancesResponseType> getStopInstancesResponse() {
        if (stopInstancesResponse == null) {
            stopInstancesResponse = new ArrayList<StopInstancesResponseType>();
        }
        return this.stopInstancesResponse;
    }

    /**
     * Gets the value of the suspendProcessesResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the suspendProcessesResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSuspendProcessesResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuspendProcessesResponseType }
     * 
     * 
     */
    public List<SuspendProcessesResponseType> getSuspendProcessesResponse() {
        if (suspendProcessesResponse == null) {
            suspendProcessesResponse = new ArrayList<SuspendProcessesResponseType>();
        }
        return this.suspendProcessesResponse;
    }

    /**
     * Gets the value of the startInstancesResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the startInstancesResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStartInstancesResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StartInstancesResponseType }
     * 
     * 
     */
    public List<StartInstancesResponseType> getStartInstancesResponse() {
        if (startInstancesResponse == null) {
            startInstancesResponse = new ArrayList<StartInstancesResponseType>();
        }
        return this.startInstancesResponse;
    }

    /**
     * Gets the value of the resumeProcessesResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resumeProcessesResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResumeProcessesResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResumeProcessesResponseType }
     * 
     * 
     */
    public List<ResumeProcessesResponseType> getResumeProcessesResponse() {
        if (resumeProcessesResponse == null) {
            resumeProcessesResponse = new ArrayList<ResumeProcessesResponseType>();
        }
        return this.resumeProcessesResponse;
    }

    /**
     * Gets the value of the restoreDBInstanceFromDBSnapshotResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restoreDBInstanceFromDBSnapshotResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestoreDBInstanceFromDBSnapshotResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RestoreDBInstanceFromDBSnapshotResponseType }
     * 
     * 
     */
    public List<RestoreDBInstanceFromDBSnapshotResponseType> getRestoreDBInstanceFromDBSnapshotResponse() {
        if (restoreDBInstanceFromDBSnapshotResponse == null) {
            restoreDBInstanceFromDBSnapshotResponse = new ArrayList<RestoreDBInstanceFromDBSnapshotResponseType>();
        }
        return this.restoreDBInstanceFromDBSnapshotResponse;
    }

/**
     * Gets the value of the describeInstancesResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeInstancesResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeInstancesResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeInstancesResponseType }
     * 
     * 
     */
    public List<DescribeInstancesResponseType> getDescribeInstancesResponse() {
        if (describeInstancesResponse == null) {
            describeInstancesResponse = new ArrayList<DescribeInstancesResponseType>();
        }
        return this.describeInstancesResponse;
    }

    /**
     * Gets the value of the describeKeyPairsResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeKeyPairsResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeKeyPairsResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeKeyPairsResponseType }
     * 
     * 
     */
    public List<DescribeKeyPairsResponseType> getDescribeKeyPairsResponse() {
        if (describeKeyPairsResponse == null) {
            describeKeyPairsResponse = new ArrayList<DescribeKeyPairsResponseType>();
        }
        return this.describeKeyPairsResponse;
    }

    /**
     * Gets the value of the describeSecurityGroupsResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeSecurityGroupsResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeSecurityGroupsResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeSecurityGroupsResponseType }
     * 
     * 
     */
    public List<DescribeSecurityGroupsResponseType> getDescribeSecurityGroupsResponse() {
        if (describeSecurityGroupsResponse == null) {
            describeSecurityGroupsResponse = new ArrayList<DescribeSecurityGroupsResponseType>();
        }
        return this.describeSecurityGroupsResponse;
    }

    /**
     * Gets the value of the describeInstances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeInstances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeInstances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeInstancesResponseType }
     * 
     * 
     */
    public List<DescribeInstancesResponseType> getDescribeInstances() {
        if (describeInstances == null) {
            describeInstances = new ArrayList<DescribeInstancesResponseType>();
        }
        return this.describeInstances;
    }

    /**
     * Gets the value of the describeLoadBalancersResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeLoadBalancersResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeLoadBalancersResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeLoadBalancersResponseType }
     * 
     * 
     */
    public List<DescribeLoadBalancersResponseType> getDescribeLoadBalancersResponse() {
        if (describeLoadBalancersResponse == null) {
            describeLoadBalancersResponse = new ArrayList<DescribeLoadBalancersResponseType>();
        }
        return this.describeLoadBalancersResponse;
    }

    /**
     * Gets the value of the describeLaunchConfigurationsResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeLaunchConfigurationsResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeLaunchConfigurationsResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeLaunchConfigurationsResponseType }
     * 
     * 
     */
    public List<DescribeLaunchConfigurationsResponseType> getDescribeLaunchConfigurationsResponse() {
        if (describeLaunchConfigurationsResponse == null) {
            describeLaunchConfigurationsResponse = new ArrayList<DescribeLaunchConfigurationsResponseType>();
        }
        return this.describeLaunchConfigurationsResponse;
    }

    /**
     * Gets the value of the describeScalingProcessResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeScalingProcessResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeScalingProcessResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeScalingProcessTypesResponse }
     * 
     * 
     */
    public List<DescribeScalingProcessTypesResponse> getDescribeScalingProcessResponse() {
        if (describeScalingProcessResponse == null) {
            describeScalingProcessResponse = new ArrayList<DescribeScalingProcessTypesResponse>();
        }
        return this.describeScalingProcessResponse;
    }

    /**
     * Gets the value of the describeAutoScalingGroupsResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeAutoScalingGroupsResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeAutoScalingGroupsResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeAutoScalingGroupsResponseType }
     * 
     * 
     */
    public List<DescribeAutoScalingGroupsResponseType> getDescribeAutoScalingGroupsResponse() {
        if (describeAutoScalingGroupsResponse == null) {
            describeAutoScalingGroupsResponse = new ArrayList<DescribeAutoScalingGroupsResponseType>();
        }
        return this.describeAutoScalingGroupsResponse;
    }

    /**
     * Gets the value of the describeDBSecurityGroupsResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeDBSecurityGroupsResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeDBSecurityGroupsResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeDBSecurityGroupsResponseType }
     * 
     * 
     */
    public List<DescribeDBSecurityGroupsResponseType> getDescribeDBSecurityGroupsResponse() {
        if (describeDBSecurityGroupsResponse == null) {
            describeDBSecurityGroupsResponse = new ArrayList<DescribeDBSecurityGroupsResponseType>();
        }
        return this.describeDBSecurityGroupsResponse;
    }

    /**
     * Gets the value of the describeDBInstancesResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeDBInstancesResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeDBInstancesResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeDBInstancesResponseType }
     * 
     * 
     */
    public List<DescribeDBInstancesResponseType> getDescribeDBInstancesResponse() {
        if (describeDBInstancesResponse == null) {
            describeDBInstancesResponse = new ArrayList<DescribeDBInstancesResponseType>();
        }
        return this.describeDBInstancesResponse;
    }

	public void setInstanceDetails(List<Ec2InstanceResponse> instanceDetails) {
		this.instanceDetails = instanceDetails;
	}

	public void setCreateKeyPairDetails(
			List<CreateKeyPairResponse> createKeyPairDetails) {
		this.createKeyPairDetails = createKeyPairDetails;
	}

	public void setLoadBalancerDetails(
			List<LoadBalancerResponse> loadBalancerDetails) {
		this.loadBalancerDetails = loadBalancerDetails;
	}

	public void setCreateAppCookieStickinessPolicyDetails(
			List<CreateAppCookieStickinessPolicyResponse> createAppCookieStickinessPolicyDetails) {
		this.createAppCookieStickinessPolicyDetails = createAppCookieStickinessPolicyDetails;
	}

	public void setCreateLBCookieStickinessPolicyDetails(
			List<CreateLBCookieStickinessPolicyResponse> createLBCookieStickinessPolicyDetails) {
		this.createLBCookieStickinessPolicyDetails = createLBCookieStickinessPolicyDetails;
	}

	public void setCreateLaunchConfigurationDetails(
			List<CreateLaunchConfigurationResponse> createLaunchConfigurationDetails) {
		this.createLaunchConfigurationDetails = createLaunchConfigurationDetails;
	}

	public void setCreateCreateAutoScalingGroupGroupDetails(
			List<CreateAutoScalingGroupResponse> createAutoScalingGroupDetails) {
		this.createAutoScalingGroupDetails = createAutoScalingGroupDetails;
	}

	public void setAddSecurityGroupRuleDetails(
			List<AddSecurityGroupRuleResponse> addSecurityGroupRuleDetails) {
		this.addSecurityGroupRuleDetails = addSecurityGroupRuleDetails;
	}

	public void setDeleteSecurityGroupRuleDetails(
			List<DeleteSecurityGroupRuleDetailsType> deleteSecurityGroupRuleDetails) {
		this.deleteSecurityGroupRuleDetails = deleteSecurityGroupRuleDetails;
	}

	public void setCreateSecurityGroupDetails(
			List<CreateSecurityGroupResponse> createSecurityGroupDetails) {
		this.createSecurityGroupDetails = createSecurityGroupDetails;
	}

	public void setAuthorizeDBSecurityGroupIngressDetails(
			List<AuthorizeDBSecurityGroupIngressResponse> authorizeDBSecurityGroupIngressDetails) {
		this.authorizeDBSecurityGroupIngressDetails = authorizeDBSecurityGroupIngressDetails;
	}

	public void setCreateDBSecurityGroupDetails(
			List<CreateDBSecurityGroupResponse> createDBSecurityGroupDetails) {
		this.createDBSecurityGroupDetails = createDBSecurityGroupDetails;
	}

	public void setLaunchRDSInstanceDetails(
			List<CreateDBInstanceResponse> launchRDSInstanceDetails) {
		this.launchRDSInstanceDetails = launchRDSInstanceDetails;
	}

	public void setPutScalingPolicyDetails(
			List<PutScalingPolicyResponse> putScalingPolicyDetails) {
		this.putScalingPolicyDetails = putScalingPolicyDetails;
	}

	public void setPutMetricAlarmDetails(
			List<PutMetricAlarmDetailsType> putMetricAlarmDetails) {
		this.putMetricAlarmDetails = putMetricAlarmDetails;
	}

	public void setGetMetricStatisticsDetails(
			List<GetMetricStatisticsDetailsType> getMetricStatisticsDetails) {
		this.getMetricStatisticsDetails = getMetricStatisticsDetails;
	}

	public void setCreateDBSnapshotDetails(
			List<CreateDBSnapshotDetailsType> createDBSnapshotDetails) {
		this.createDBSnapshotDetails = createDBSnapshotDetails;
	}

	public void setDeleteLaunchConfigurationResponse(
			List<DeleteLaunchConfigurationResponseType> deleteLaunchConfigurationResponse) {
		this.deleteLaunchConfigurationResponse = deleteLaunchConfigurationResponse;
	}

	public void setDeleteLoadBalancerResponse(
			List<DeleteLoadBalancerResponseType> deleteLoadBalancerResponse) {
		this.deleteLoadBalancerResponse = deleteLoadBalancerResponse;
	}

	public void setTerminateInstancesResponse(
			List<TerminateInstancesResponseType> terminateInstancesResponse) {
		this.terminateInstancesResponse = terminateInstancesResponse;
	}

	public void setDeleteDBInstanceResponse(
			List<DeleteDBInstanceResponseType> deleteDBInstanceResponse) {
		this.deleteDBInstanceResponse = deleteDBInstanceResponse;
	}

	public void setDeleteKeyPairResponse(
			List<DeleteKeyPairResponseType> deleteKeyPairResponse) {
		this.deleteKeyPairResponse = deleteKeyPairResponse;
	}

	public void setDeleteSecurityGroupResponse(
			List<DeleteSecurityGroupResponseType> deleteSecurityGroupResponse) {
		this.deleteSecurityGroupResponse = deleteSecurityGroupResponse;
	}

	public void setDeleteDBSecurityGroupResponse(
			List<DeleteDBSecurityGroupResponseType> deleteDBSecurityGroupResponse) {
		this.deleteDBSecurityGroupResponse = deleteDBSecurityGroupResponse;
	}

	public void setStopInstancesResponse(
			List<StopInstancesResponseType> stopInstancesResponse) {
		this.stopInstancesResponse = stopInstancesResponse;
	}

	public void setSuspendProcessesResponse(
			List<SuspendProcessesResponseType> suspendProcessesResponse) {
		this.suspendProcessesResponse = suspendProcessesResponse;
	}

	public void setUpdateAutoScalingGroupResponse(
			List<UpdateAutoScalingGroupResponseType> updateAutoScalingGroupResponse) {
		this.updateAutoScalingGroupResponse = updateAutoScalingGroupResponse;
	}

	public void setDeleteAutoScalingGroupResponse(
			List<DeleteAutoScalingGroupResponseType> deleteAutoScalingGroupResponse) {
		this.deleteAutoScalingGroupResponse = deleteAutoScalingGroupResponse;
	}

	public void setStartInstancesResponse(
			List<StartInstancesResponseType> startInstancesResponse) {
		this.startInstancesResponse = startInstancesResponse;
	}

	public void setResumeProcessesResponse(
			List<ResumeProcessesResponseType> resumeProcessesResponse) {
		this.resumeProcessesResponse = resumeProcessesResponse;
	}

	public void setRestoreDBInstanceFromDBSnapshotResponse(
			List<RestoreDBInstanceFromDBSnapshotResponseType> restoreDBInstanceFromDBSnapshotResponse) {
		this.restoreDBInstanceFromDBSnapshotResponse = restoreDBInstanceFromDBSnapshotResponse;
	}

	public void setDescribeInstancesResponse(
			List<DescribeInstancesResponseType> describeInstancesResponse) {
		this.describeInstancesResponse = describeInstancesResponse;
	}

	public void setDescribeKeyPairsResponse(
			List<DescribeKeyPairsResponseType> describeKeyPairsResponse) {
		this.describeKeyPairsResponse = describeKeyPairsResponse;
	}

	public void setDescribeSecurityGroupsResponse(
			List<DescribeSecurityGroupsResponseType> describeSecurityGroupsResponse) {
		this.describeSecurityGroupsResponse = describeSecurityGroupsResponse;
	}

	public void setDescribeInstances(
			List<DescribeInstancesResponseType> describeInstances) {
		this.describeInstances = describeInstances;
	}

	public void setDescribeLoadBalancersResponse(
			List<DescribeLoadBalancersResponseType> describeLoadBalancersResponse) {
		this.describeLoadBalancersResponse = describeLoadBalancersResponse;
	}

	public void setDescribeLaunchConfigurationsResponse(
			List<DescribeLaunchConfigurationsResponseType> describeLaunchConfigurationsResponse) {
		this.describeLaunchConfigurationsResponse = describeLaunchConfigurationsResponse;
	}

	public void setDescribeScalingProcessResponse(
			List<DescribeScalingProcessTypesResponse> describeScalingProcessResponse) {
		this.describeScalingProcessResponse = describeScalingProcessResponse;
	}

	public void setDescribeAutoScalingGroupsResponse(
			List<DescribeAutoScalingGroupsResponseType> describeAutoScalingGroupsResponse) {
		this.describeAutoScalingGroupsResponse = describeAutoScalingGroupsResponse;
	}

	public void setDescribeDBSecurityGroupsResponse(
			List<DescribeDBSecurityGroupsResponseType> describeDBSecurityGroupsResponse) {
		this.describeDBSecurityGroupsResponse = describeDBSecurityGroupsResponse;
	}

	public void setDescribeDBInstancesResponse(
			List<DescribeDBInstancesResponseType> describeDBInstancesResponse) {
		this.describeDBInstancesResponse = describeDBInstancesResponse;
	}

	public void setCreateDBInstanceReadReplicaDetails(
			List<CreateDBInstanceReadReplicaResponse> createDBInstanceReadReplicaDetails) {
		this.createDBInstanceReadReplicaDetails = createDBInstanceReadReplicaDetails;
	}
	
}
