//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.27 at 01:43:51 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PoliciesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PoliciesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppCookieStickinessPolicies" type="{}AppCookieStickinessPoliciesType" minOccurs="0"/>
 *         &lt;element name="LBCookieStickinessPolicies" type="{}LBCookieStickinessPoliciesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PoliciesType", propOrder = {
    "appCookieStickinessPolicies",
    "lbCookieStickinessPolicies"
})
public class PoliciesType {

    @XmlElement(name = "AppCookieStickinessPolicies")
    protected AppCookieStickinessPoliciesType appCookieStickinessPolicies;
    @XmlElement(name = "LBCookieStickinessPolicies")
    protected LBCookieStickinessPoliciesType lbCookieStickinessPolicies;

    /**
     * Gets the value of the appCookieStickinessPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link AppCookieStickinessPoliciesType }
     *     
     */
    public AppCookieStickinessPoliciesType getAppCookieStickinessPolicies() {
        return appCookieStickinessPolicies;
    }

    /**
     * Sets the value of the appCookieStickinessPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppCookieStickinessPoliciesType }
     *     
     */
    public void setAppCookieStickinessPolicies(AppCookieStickinessPoliciesType value) {
        this.appCookieStickinessPolicies = value;
    }

    /**
     * Gets the value of the lbCookieStickinessPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link LBCookieStickinessPoliciesType }
     *     
     */
    public LBCookieStickinessPoliciesType getLBCookieStickinessPolicies() {
        return lbCookieStickinessPolicies;
    }

    /**
     * Sets the value of the lbCookieStickinessPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link LBCookieStickinessPoliciesType }
     *     
     */
    public void setLBCookieStickinessPolicies(LBCookieStickinessPoliciesType value) {
        this.lbCookieStickinessPolicies = value;
    }

}
