//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.02 at 01:05:27 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PutMetricAlarmDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PutMetricAlarmDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AlarmName" type="{}AlarmName"/>
 *         &lt;element name="AlarmDescription" type="{}AlarmDescription" minOccurs="0"/>
 *         &lt;element name="ActionsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="OKActions" type="{}ResourceList" minOccurs="0"/>
 *         &lt;element name="AlarmActions" type="{}ResourceList" minOccurs="0"/>
 *         &lt;element name="InsufficientDataActions" type="{}ResourceList" minOccurs="0"/>
 *         &lt;element name="MetricName" type="{}MetricName"/>
 *         &lt;element name="Namespace" type="{}Namespace"/>
 *         &lt;element name="Statistic" type="{}Statistic"/>
 *         &lt;element name="Dimensions" type="{}Dimensions" minOccurs="0"/>
 *         &lt;element name="Period" type="{}Period"/>
 *         &lt;element name="Unit" type="{}StandardUnit" minOccurs="0"/>
 *         &lt;element name="EvaluationPeriods" type="{}EvaluationPeriods"/>
 *         &lt;element name="Threshold" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ComparisonOperator" type="{}ComparisonOperator"/>
 *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PutMetricAlarmDetailsType", propOrder = {
    "alarmName",
    "alarmDescription",
    "actionsEnabled",
    "okActions",
    "alarmActions",
    "insufficientDataActions",
    "metricName",
    "namespace",
    "statistic",
    "dimensions",
    "period",
    "unit",
    "evaluationPeriods",
    "threshold",
    "comparisonOperator",
    "region",
    "status"
})
public class PutMetricAlarmDetailsType {

    @XmlElement(name = "AlarmName", required = true)
    protected String alarmName;
    @XmlElement(name = "AlarmDescription")
    protected String alarmDescription;
    @XmlElement(name = "ActionsEnabled")
    protected Boolean actionsEnabled;
    @XmlElement(name = "OKActions")
    protected ResourceList okActions;
    @XmlElement(name = "AlarmActions")
    protected ResourceList alarmActions;
    @XmlElement(name = "InsufficientDataActions")
    protected ResourceList insufficientDataActions;
    @XmlElement(name = "MetricName", required = true)
    protected String metricName;
    @XmlElement(name = "Namespace", required = true)
    protected String namespace;
    @XmlElement(name = "Statistic", required = true)
    protected Statistic statistic;
    @XmlElement(name = "Dimensions")
    protected Dimensions dimensions;
    @XmlElement(name = "Period", required = true)
    protected Integer period;
    @XmlElement(name = "Unit")
    protected StandardUnit unit;
    @XmlElement(name = "EvaluationPeriods", required = true)
    protected Integer evaluationPeriods;
    @XmlElement(name = "Threshold")
    protected double threshold;
    @XmlElement(name = "ComparisonOperator", required = true)
    protected ComparisonOperator comparisonOperator;
    @XmlElement(name = "Region", required = true)
    protected String region;
    @XmlElement(name = "Status", required = true)
    protected String status;

    public PutMetricAlarmDetailsType() {}
	public PutMetricAlarmDetailsType(PutMetricAlarmType putMetricAlarmType) {
		
		this.alarmName 			= putMetricAlarmType.getAlarmName();
		this.alarmDescription 	= putMetricAlarmType.getAlarmDescription();
		this.actionsEnabled 	= putMetricAlarmType.isActionsEnabled();
		this.okActions 			= putMetricAlarmType.getOKActions();
		this.alarmActions 		= putMetricAlarmType.getAlarmActions();
		this.insufficientDataActions = putMetricAlarmType.getInsufficientDataActions();
		this.metricName 		= putMetricAlarmType.getMetricName();
		this.namespace 			= putMetricAlarmType.getNamespace();
		this.statistic 			= putMetricAlarmType.getStatistic();		
		this.dimensions = putMetricAlarmType.getDimensions();
		this.period = putMetricAlarmType.getPeriod();
		this.unit = putMetricAlarmType.getUnit();
		this.evaluationPeriods = putMetricAlarmType.getEvaluationPeriods();
		this.threshold = putMetricAlarmType.getThreshold();
		this.comparisonOperator = putMetricAlarmType.getComparisonOperator();
	}

	/**
     * Gets the value of the alarmName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlarmName() {
        return alarmName;
    }

    /**
     * Sets the value of the alarmName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlarmName(String value) {
        this.alarmName = value;
    }

    /**
     * Gets the value of the alarmDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlarmDescription() {
        return alarmDescription;
    }

    /**
     * Sets the value of the alarmDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlarmDescription(String value) {
        this.alarmDescription = value;
    }

    /**
     * Gets the value of the actionsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActionsEnabled() {
        return actionsEnabled;
    }

    /**
     * Sets the value of the actionsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActionsEnabled(Boolean value) {
        this.actionsEnabled = value;
    }

    /**
     * Gets the value of the okActions property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceList }
     *     
     */
    public ResourceList getOKActions() {
        return okActions;
    }

    /**
     * Sets the value of the okActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceList }
     *     
     */
    public void setOKActions(ResourceList value) {
        this.okActions = value;
    }

    /**
     * Gets the value of the alarmActions property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceList }
     *     
     */
    public ResourceList getAlarmActions() {
        return alarmActions;
    }

    /**
     * Sets the value of the alarmActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceList }
     *     
     */
    public void setAlarmActions(ResourceList value) {
        this.alarmActions = value;
    }

    /**
     * Gets the value of the insufficientDataActions property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceList }
     *     
     */
    public ResourceList getInsufficientDataActions() {
        return insufficientDataActions;
    }

    /**
     * Sets the value of the insufficientDataActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceList }
     *     
     */
    public void setInsufficientDataActions(ResourceList value) {
        this.insufficientDataActions = value;
    }

    /**
     * Gets the value of the metricName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetricName() {
        return metricName;
    }

    /**
     * Sets the value of the metricName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetricName(String value) {
        this.metricName = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

    /**
     * Gets the value of the statistic property.
     * 
     * @return
     *     possible object is
     *     {@link Statistic }
     *     
     */
    public Statistic getStatistic() {
        return statistic;
    }

    /**
     * Sets the value of the statistic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statistic }
     *     
     */
    public void setStatistic(Statistic value) {
        this.statistic = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link Dimensions }
     *     
     */
    public Dimensions getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dimensions }
     *     
     */
    public void setDimensions(Dimensions value) {
        this.dimensions = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPeriod(Integer value) {
        this.period = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link StandardUnit }
     *     
     */
    public StandardUnit getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardUnit }
     *     
     */
    public void setUnit(StandardUnit value) {
        this.unit = value;
    }

    /**
     * Gets the value of the evaluationPeriods property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getEvaluationPeriods() {
        return evaluationPeriods;
    }

    /**
     * Sets the value of the evaluationPeriods property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEvaluationPeriods(Integer value) {
        this.evaluationPeriods = value;
    }

    /**
     * Gets the value of the threshold property.
     * 
     */
    public double getThreshold() {
        return threshold;
    }

    /**
     * Sets the value of the threshold property.
     * 
     */
    public void setThreshold(double value) {
        this.threshold = value;
    }

    /**
     * Gets the value of the comparisonOperator property.
     * 
     * @return
     *     possible object is
     *     {@link ComparisonOperator }
     *     
     */
    public ComparisonOperator getComparisonOperator() {
        return comparisonOperator;
    }

    /**
     * Sets the value of the comparisonOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComparisonOperator }
     *     
     */
    public void setComparisonOperator(ComparisonOperator value) {
        this.comparisonOperator = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
