//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.13 at 04:18:43 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PutScalingPolicyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PutScalingPolicyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AutoScalingGroupName" type="{}ASGResourceName"/>
 *         &lt;element name="PolicyName" type="{}XmlStringMaxLen255"/>
 *         &lt;element name="ScalingAdjustment" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AdjustmentType" type="{}XmlStringMaxLen255"/>
 *         &lt;element name="Cooldown" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PutScalingPolicyType", propOrder = {
    "autoScalingGroupName",
    "policyName",
    "scalingAdjustment",
    "adjustmentType",
    "cooldown",
    "region"
})
public class PutScalingPolicyType {

    @XmlElement(name = "AutoScalingGroupName", required = true)
    protected String autoScalingGroupName;
    @XmlElement(name = "PolicyName", required = true)
    protected String policyName;
    @XmlElement(name = "ScalingAdjustment", required = true)
    protected Integer scalingAdjustment;
    @XmlElement(name = "AdjustmentType", required = true)
    protected String adjustmentType;
    @XmlElement(name = "Cooldown")
    protected Integer cooldown;
    @XmlElement(name = "Region", required = true)
    protected String region;

    /**
     * Gets the value of the autoScalingGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoScalingGroupName() {
        return autoScalingGroupName;
    }

    /**
     * Sets the value of the autoScalingGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoScalingGroupName(String value) {
        this.autoScalingGroupName = value;
    }

    /**
     * Gets the value of the policyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyName() {
        return policyName;
    }

    /**
     * Sets the value of the policyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyName(String value) {
        this.policyName = value;
    }

    /**
     * Gets the value of the scalingAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getScalingAdjustment() {
        return scalingAdjustment;
    }

    /**
     * Sets the value of the scalingAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScalingAdjustment(Integer value) {
        this.scalingAdjustment = value;
    }

    /**
     * Gets the value of the adjustmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjustmentType() {
        return adjustmentType;
    }

    /**
     * Sets the value of the adjustmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjustmentType(String value) {
        this.adjustmentType = value;
    }

    /**
     * Gets the value of the cooldown property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getCooldown() {
        return cooldown;
    }

    /**
     * Sets the value of the cooldown property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCooldown(Integer value) {
        this.cooldown = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

}
