//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.04 at 01:09:11 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourcesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourcesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CreateSecurityGroup" type="{}CreateSecurityGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AddSecurityGroupRule" type="{}AddSecurityGroupRuleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateKeyPair" type="{}CreateKeyPairType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Ec2Instance" type="{}Ec2InstanceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LoadBalancer" type="{}LoadBalancerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateAppCookieStickinessPolicy" type="{}CreateAppCookieStickinessPolicyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateLBCookieStickinessPolicy" type="{}CreateLBCookieStickinessPolicyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateLaunchConfiguration" type="{}CreateLaunchConfigurationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateAutoScalingGroup" type="{}CreateAutoScalingGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PutScalingPolicy" type="{}PutScalingPolicyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LaunchRDSInstance" type="{}CreateDBInstanceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PutMetricAlarm" type="{}PutMetricAlarmType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateDBSecurityGroup" type="{}CreateDBSecurityGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AuthorizeDBSecurityGroupIngress" type="{}AuthorizeDBSecurityGroupIngressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateDBInstanceReadReplica" type="{}CreateDBInstanceReadReplicaType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreateDBSnapshot" type="{}CreateDBSnapshotType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GetMetricStatistics" type="{}GetMetricStatisticsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UpdateAutoScalingGroupRequest" type="{}UpdateAutoScalingGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteAutoScalingGroupRequest" type="{}DeleteAutoScalingGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteLaunchConfigurationRequest" type="{}DeleteLaunchConfigurationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteLoadBalancerRequest" type="{}DeleteLoadBalancerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TerminateInstancesRequest" type="{}TerminateInstancesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteDBInstanceRequest" type="{}DeleteDBInstanceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteKeyPairRequest" type="{}DeleteKeyPairType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteSecurityGroupRule" type="{}DeleteSecurityGroupRuleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteSecurityGroupRequest" type="{}DeleteSecurityGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeleteDBSecurityGroupRequest" type="{}DeleteDBSecurityGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SuspendProcesses" type="{}SuspendProcessesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StopInstances" type="{}StopInstancesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StartInstances" type="{}StartInstancesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ResumeProcesses" type="{}ResumeProcessesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RestoreDBInstanceFromDBSnapshot" type="{}RestoreDBInstanceFromDBSnapshotType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeKeyPairs" type="{}DescribeKeyPairsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeSecurityGroups" type="{}DescribeSecurityGroupsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeInstances" type="{}DescribeInstancesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeLoadBalancers" type="{}DescribeLoadBalancersType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeLaunchConfigurations" type="{}DescribeLaunchConfigurationsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeScalingProcess" type="{}DescribeScalingProcessTypes" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeAutoScalingGroups" type="{}DescribeAutoScalingGroupsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeDBSecurityGroups" type="{}DescribeDBSecurityGroupsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DescribeDBInstances" type="{}DescribeDBInstancesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourcesType", propOrder = {
    "createSecurityGroup",
    "addSecurityGroupRule",
    "createKeyPair",
    "ec2Instance",
    "loadBalancer",
    "createAppCookieStickinessPolicy",
    "createLBCookieStickinessPolicy",
    "createLaunchConfiguration",
    "createAutoScalingGroup",
    "putScalingPolicy",
    "launchRDSInstance",
    "putMetricAlarm",
    "createDBSecurityGroup",
    "authorizeDBSecurityGroupIngress",
    "createDBInstanceReadReplica",
    "createDBSnapshot",
    "getMetricStatistics",
    "updateAutoScalingGroupRequest",
    "deleteAutoScalingGroupRequest",
    "deleteLaunchConfigurationRequest",
    "deleteLoadBalancerRequest",
    "terminateInstancesRequest",
    "deleteDBInstanceRequest",
    "deleteKeyPairRequest",
    "deleteSecurityGroupRule",
    "deleteSecurityGroupRequest",
    "deleteDBSecurityGroupRequest",
    "suspendProcesses",
    "stopInstances",
    "startInstances",
    "resumeProcesses",
    "restoreDBInstanceFromDBSnapshot",
    "describeKeyPairs",
    "describeSecurityGroups",
    "describeInstances",
    "describeLoadBalancers",
    "describeLaunchConfigurations",
    "describeScalingProcess",
    "describeAutoScalingGroups",
    "describeDBSecurityGroups",
    "describeDBInstances"
})
public class Resources {

    @XmlElement(name = "CreateSecurityGroup")
    protected List<CreateSecurityGroupType> createSecurityGroup;
    @XmlElement(name = "AddSecurityGroupRule")
    protected List<AddSecurityGroupRuleType> addSecurityGroupRule;
    @XmlElement(name = "CreateKeyPair")
    protected List<CreateKeyPairType> createKeyPair;
    @XmlElement(name = "Ec2Instance")
    protected List<Ec2InstanceType> ec2Instance;
    @XmlElement(name = "LoadBalancer")
    protected List<LoadBalancerType> loadBalancer;
    @XmlElement(name = "CreateAppCookieStickinessPolicy")
    protected List<CreateAppCookieStickinessPolicyType> createAppCookieStickinessPolicy;
    @XmlElement(name = "CreateLBCookieStickinessPolicy")
    protected List<CreateLBCookieStickinessPolicyType> createLBCookieStickinessPolicy;
    @XmlElement(name = "CreateLaunchConfiguration")
    protected List<CreateLaunchConfigurationType> createLaunchConfiguration;
    @XmlElement(name = "CreateAutoScalingGroup")
    protected List<CreateAutoScalingGroupType> createAutoScalingGroup;
    @XmlElement(name = "PutScalingPolicy")
    protected List<PutScalingPolicyType> putScalingPolicy;
    @XmlElement(name = "LaunchRDSInstance")
    protected List<CreateDBInstanceType> launchRDSInstance;
    @XmlElement(name = "PutMetricAlarm")
    protected List<PutMetricAlarmType> putMetricAlarm;
    @XmlElement(name = "CreateDBSecurityGroup")
    protected List<CreateDBSecurityGroupType> createDBSecurityGroup;
    @XmlElement(name = "AuthorizeDBSecurityGroupIngress")
    protected List<AuthorizeDBSecurityGroupIngressType> authorizeDBSecurityGroupIngress;
    @XmlElement(name = "CreateDBInstanceReadReplica")
    protected List<CreateDBInstanceReadReplicaType> createDBInstanceReadReplica;
    @XmlElement(name = "CreateDBSnapshot")
    protected List<CreateDBSnapshotType> createDBSnapshot;
    @XmlElement(name = "GetMetricStatistics")
    protected List<GetMetricStatisticsType> getMetricStatistics;
    @XmlElement(name = "UpdateAutoScalingGroupRequest")
    protected List<UpdateAutoScalingGroupType> updateAutoScalingGroupRequest;
    @XmlElement(name = "DeleteAutoScalingGroupRequest")
    protected List<DeleteAutoScalingGroupType> deleteAutoScalingGroupRequest;
    @XmlElement(name = "DeleteLaunchConfigurationRequest")
    protected List<DeleteLaunchConfigurationType> deleteLaunchConfigurationRequest;
    @XmlElement(name = "DeleteLoadBalancerRequest")
    protected List<DeleteLoadBalancerType> deleteLoadBalancerRequest;
    @XmlElement(name = "TerminateInstancesRequest")
    protected List<TerminateInstancesType> terminateInstancesRequest;
    @XmlElement(name = "DeleteDBInstanceRequest")
    protected List<DeleteDBInstanceType> deleteDBInstanceRequest;
    @XmlElement(name = "DeleteKeyPairRequest")
    protected List<DeleteKeyPairType> deleteKeyPairRequest;
    @XmlElement(name = "DeleteSecurityGroupRule")
    protected List<DeleteSecurityGroupRuleType> deleteSecurityGroupRule;
    @XmlElement(name = "DeleteSecurityGroupRequest")
    protected List<DeleteSecurityGroupType> deleteSecurityGroupRequest;
    @XmlElement(name = "DeleteDBSecurityGroupRequest")
    protected List<DeleteDBSecurityGroupType> deleteDBSecurityGroupRequest;
    @XmlElement(name = "SuspendProcesses")
    protected List<SuspendProcessesType> suspendProcesses;
    @XmlElement(name = "StopInstances")
    protected List<StopInstancesType> stopInstances;
    @XmlElement(name = "StartInstances")
    protected List<StartInstancesType> startInstances;
    @XmlElement(name = "ResumeProcesses")
    protected List<ResumeProcessesType> resumeProcesses;
    @XmlElement(name = "RestoreDBInstanceFromDBSnapshot")
    protected List<RestoreDBInstanceFromDBSnapshotType> restoreDBInstanceFromDBSnapshot;
    @XmlElement(name = "DescribeKeyPairs")
    protected List<DescribeKeyPairsType> describeKeyPairs;
    @XmlElement(name = "DescribeSecurityGroups")
    protected List<DescribeSecurityGroupsType> describeSecurityGroups;
    @XmlElement(name = "DescribeInstances")
    protected List<DescribeInstancesType> describeInstances;
    @XmlElement(name = "DescribeLoadBalancers")
    protected List<DescribeLoadBalancersType> describeLoadBalancers;
    @XmlElement(name = "DescribeLaunchConfigurations")
    protected List<DescribeLaunchConfigurationsType> describeLaunchConfigurations;
    @XmlElement(name = "DescribeScalingProcess")
    protected List<DescribeScalingProcessTypes> describeScalingProcess;
    @XmlElement(name = "DescribeAutoScalingGroups")
    protected List<DescribeAutoScalingGroupsType> describeAutoScalingGroups;
    @XmlElement(name = "DescribeDBSecurityGroups")
    protected List<DescribeDBSecurityGroupsType> describeDBSecurityGroups;
    @XmlElement(name = "DescribeDBInstances")
    protected List<DescribeDBInstancesType> describeDBInstances;

    /**
     * Gets the value of the createSecurityGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createSecurityGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateSecurityGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateSecurityGroupType }
     * 
     * 
     */
    public List<CreateSecurityGroupType> getCreateSecurityGroup() {
        if (createSecurityGroup == null) {
            createSecurityGroup = new ArrayList<CreateSecurityGroupType>();
        }
        return this.createSecurityGroup;
    }

    /**
     * Gets the value of the addSecurityGroupRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addSecurityGroupRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddSecurityGroupRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddSecurityGroupRuleType }
     * 
     * 
     */
    public List<AddSecurityGroupRuleType> getAddSecurityGroupRule() {
        if (addSecurityGroupRule == null) {
            addSecurityGroupRule = new ArrayList<AddSecurityGroupRuleType>();
        }
        return this.addSecurityGroupRule;
    }

    /**
     * Gets the value of the createKeyPair property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createKeyPair property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateKeyPair().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateKeyPairType }
     * 
     * 
     */
    public List<CreateKeyPairType> getCreateKeyPair() {
        if (createKeyPair == null) {
            createKeyPair = new ArrayList<CreateKeyPairType>();
        }
        return this.createKeyPair;
    }

    /**
     * Gets the value of the ec2Instance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ec2Instance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEc2Instance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ec2InstanceType }
     * 
     * 
     */
    public List<Ec2InstanceType> getEc2Instance() {
        if (ec2Instance == null) {
            ec2Instance = new ArrayList<Ec2InstanceType>();
        }
        return this.ec2Instance;
    }

    /**
     * Gets the value of the loadBalancer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loadBalancer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoadBalancer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoadBalancerType }
     * 
     * 
     */
    public List<LoadBalancerType> getLoadBalancer() {
        if (loadBalancer == null) {
            loadBalancer = new ArrayList<LoadBalancerType>();
        }
        return this.loadBalancer;
    }

    /**
     * Gets the value of the createAppCookieStickinessPolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createAppCookieStickinessPolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateAppCookieStickinessPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateAppCookieStickinessPolicyType }
     * 
     * 
     */
    public List<CreateAppCookieStickinessPolicyType> getCreateAppCookieStickinessPolicy() {
        if (createAppCookieStickinessPolicy == null) {
            createAppCookieStickinessPolicy = new ArrayList<CreateAppCookieStickinessPolicyType>();
        }
        return this.createAppCookieStickinessPolicy;
    }

    /**
     * Gets the value of the createLBCookieStickinessPolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createLBCookieStickinessPolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateLBCookieStickinessPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateLBCookieStickinessPolicyType }
     * 
     * 
     */
    public List<CreateLBCookieStickinessPolicyType> getCreateLBCookieStickinessPolicy() {
        if (createLBCookieStickinessPolicy == null) {
            createLBCookieStickinessPolicy = new ArrayList<CreateLBCookieStickinessPolicyType>();
        }
        return this.createLBCookieStickinessPolicy;
    }

    /**
     * Gets the value of the createLaunchConfiguration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createLaunchConfiguration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateLaunchConfiguration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateLaunchConfigurationType }
     * 
     * 
     */
    public List<CreateLaunchConfigurationType> getCreateLaunchConfiguration() {
        if (createLaunchConfiguration == null) {
            createLaunchConfiguration = new ArrayList<CreateLaunchConfigurationType>();
        }
        return this.createLaunchConfiguration;
    }

    /**
     * Gets the value of the createAutoScalingGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createAutoScalingGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateAutoScalingGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateAutoScalingGroupType }
     * 
     * 
     */
    public List<CreateAutoScalingGroupType> getCreateAutoScalingGroup() {
        if (createAutoScalingGroup == null) {
            createAutoScalingGroup = new ArrayList<CreateAutoScalingGroupType>();
        }
        return this.createAutoScalingGroup;
    }

    /**
     * Gets the value of the putScalingPolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the putScalingPolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPutScalingPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PutScalingPolicyType }
     * 
     * 
     */
    public List<PutScalingPolicyType> getPutScalingPolicy() {
        if (putScalingPolicy == null) {
            putScalingPolicy = new ArrayList<PutScalingPolicyType>();
        }
        return this.putScalingPolicy;
    }

    /**
     * Gets the value of the launchRDSInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the launchRDSInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLaunchRDSInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateDBInstanceType }
     * 
     * 
     */
    public List<CreateDBInstanceType> getLaunchRDSInstance() {
        if (launchRDSInstance == null) {
            launchRDSInstance = new ArrayList<CreateDBInstanceType>();
        }
        return this.launchRDSInstance;
    }

    /**
     * Gets the value of the putMetricAlarm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the putMetricAlarm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPutMetricAlarm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PutMetricAlarmType }
     * 
     * 
     */
    public List<PutMetricAlarmType> getPutMetricAlarm() {
        if (putMetricAlarm == null) {
            putMetricAlarm = new ArrayList<PutMetricAlarmType>();
        }
        return this.putMetricAlarm;
    }

    /**
     * Gets the value of the createDBSecurityGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createDBSecurityGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateDBSecurityGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateDBSecurityGroupType }
     * 
     * 
     */
    public List<CreateDBSecurityGroupType> getCreateDBSecurityGroup() {
        if (createDBSecurityGroup == null) {
            createDBSecurityGroup = new ArrayList<CreateDBSecurityGroupType>();
        }
        return this.createDBSecurityGroup;
    }

    /**
     * Gets the value of the authorizeDBSecurityGroupIngress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorizeDBSecurityGroupIngress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorizeDBSecurityGroupIngress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorizeDBSecurityGroupIngressType }
     * 
     * 
     */
    public List<AuthorizeDBSecurityGroupIngressType> getAuthorizeDBSecurityGroupIngress() {
        if (authorizeDBSecurityGroupIngress == null) {
            authorizeDBSecurityGroupIngress = new ArrayList<AuthorizeDBSecurityGroupIngressType>();
        }
        return this.authorizeDBSecurityGroupIngress;
    }

    /**
     * Gets the value of the createDBInstanceReadReplica property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createDBInstanceReadReplica property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateDBInstanceReadReplica().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateDBInstanceReadReplicaType }
     * 
     * 
     */
    public List<CreateDBInstanceReadReplicaType> getCreateDBInstanceReadReplica() {
        if (createDBInstanceReadReplica == null) {
            createDBInstanceReadReplica = new ArrayList<CreateDBInstanceReadReplicaType>();
        }
        return this.createDBInstanceReadReplica;
    }

    /**
     * Gets the value of the createDBSnapshot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createDBSnapshot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateDBSnapshot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateDBSnapshotType }
     * 
     * 
     */
    public List<CreateDBSnapshotType> getCreateDBSnapshot() {
        if (createDBSnapshot == null) {
            createDBSnapshot = new ArrayList<CreateDBSnapshotType>();
        }
        return this.createDBSnapshot;
    }

    /**
     * Gets the value of the getMetricStatistics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the getMetricStatistics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGetMetricStatistics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetMetricStatisticsType }
     * 
     * 
     */
    public List<GetMetricStatisticsType> getGetMetricStatistics() {
        if (getMetricStatistics == null) {
            getMetricStatistics = new ArrayList<GetMetricStatisticsType>();
        }
        return this.getMetricStatistics;
    }

    /**
     * Gets the value of the updateAutoScalingGroupRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the updateAutoScalingGroupRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpdateAutoScalingGroupRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateAutoScalingGroupType }
     * 
     * 
     */
    public List<UpdateAutoScalingGroupType> getUpdateAutoScalingGroupRequest() {
        if (updateAutoScalingGroupRequest == null) {
            updateAutoScalingGroupRequest = new ArrayList<UpdateAutoScalingGroupType>();
        }
        return this.updateAutoScalingGroupRequest;
    }

    /**
     * Gets the value of the deleteAutoScalingGroupRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteAutoScalingGroupRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteAutoScalingGroupRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteAutoScalingGroupType }
     * 
     * 
     */
    public List<DeleteAutoScalingGroupType> getDeleteAutoScalingGroupRequest() {
        if (deleteAutoScalingGroupRequest == null) {
            deleteAutoScalingGroupRequest = new ArrayList<DeleteAutoScalingGroupType>();
        }
        return this.deleteAutoScalingGroupRequest;
    }

    /**
     * Gets the value of the deleteLaunchConfigurationRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteLaunchConfigurationRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteLaunchConfigurationRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteLaunchConfigurationType }
     * 
     * 
     */
    public List<DeleteLaunchConfigurationType> getDeleteLaunchConfigurationRequest() {
        if (deleteLaunchConfigurationRequest == null) {
            deleteLaunchConfigurationRequest = new ArrayList<DeleteLaunchConfigurationType>();
        }
        return this.deleteLaunchConfigurationRequest;
    }

    /**
     * Gets the value of the deleteLoadBalancerRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteLoadBalancerRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteLoadBalancerRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteLoadBalancerType }
     * 
     * 
     */
    public List<DeleteLoadBalancerType> getDeleteLoadBalancerRequest() {
        if (deleteLoadBalancerRequest == null) {
            deleteLoadBalancerRequest = new ArrayList<DeleteLoadBalancerType>();
        }
        return this.deleteLoadBalancerRequest;
    }

    /**
     * Gets the value of the terminateInstancesRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the terminateInstancesRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerminateInstancesRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TerminateInstancesType }
     * 
     * 
     */
    public List<TerminateInstancesType> getTerminateInstancesRequest() {
        if (terminateInstancesRequest == null) {
            terminateInstancesRequest = new ArrayList<TerminateInstancesType>();
        }
        return this.terminateInstancesRequest;
    }

    /**
     * Gets the value of the deleteDBInstanceRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteDBInstanceRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteDBInstanceRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteDBInstanceType }
     * 
     * 
     */
    public List<DeleteDBInstanceType> getDeleteDBInstanceRequest() {
        if (deleteDBInstanceRequest == null) {
            deleteDBInstanceRequest = new ArrayList<DeleteDBInstanceType>();
        }
        return this.deleteDBInstanceRequest;
    }

    /**
     * Gets the value of the deleteKeyPairRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteKeyPairRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteKeyPairRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteKeyPairType }
     * 
     * 
     */
    public List<DeleteKeyPairType> getDeleteKeyPairRequest() {
        if (deleteKeyPairRequest == null) {
            deleteKeyPairRequest = new ArrayList<DeleteKeyPairType>();
        }
        return this.deleteKeyPairRequest;
    }

    /**
     * Gets the value of the deleteSecurityGroupRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteSecurityGroupRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteSecurityGroupRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteSecurityGroupRuleType }
     * 
     * 
     */
    public List<DeleteSecurityGroupRuleType> getDeleteSecurityGroupRule() {
        if (deleteSecurityGroupRule == null) {
            deleteSecurityGroupRule = new ArrayList<DeleteSecurityGroupRuleType>();
        }
        return this.deleteSecurityGroupRule;
    }

    /**
     * Gets the value of the deleteSecurityGroupRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteSecurityGroupRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteSecurityGroupRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteSecurityGroupType }
     * 
     * 
     */
    public List<DeleteSecurityGroupType> getDeleteSecurityGroupRequest() {
        if (deleteSecurityGroupRequest == null) {
            deleteSecurityGroupRequest = new ArrayList<DeleteSecurityGroupType>();
        }
        return this.deleteSecurityGroupRequest;
    }

    /**
     * Gets the value of the deleteDBSecurityGroupRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deleteDBSecurityGroupRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeleteDBSecurityGroupRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteDBSecurityGroupType }
     * 
     * 
     */
    public List<DeleteDBSecurityGroupType> getDeleteDBSecurityGroupRequest() {
        if (deleteDBSecurityGroupRequest == null) {
            deleteDBSecurityGroupRequest = new ArrayList<DeleteDBSecurityGroupType>();
        }
        return this.deleteDBSecurityGroupRequest;
    }

    /**
     * Gets the value of the suspendProcesses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the suspendProcesses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSuspendProcesses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuspendProcessesType }
     * 
     * 
     */
    public List<SuspendProcessesType> getSuspendProcesses() {
        if (suspendProcesses == null) {
            suspendProcesses = new ArrayList<SuspendProcessesType>();
        }
        return this.suspendProcesses;
    }

    /**
     * Gets the value of the stopInstances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stopInstances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStopInstances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StopInstancesType }
     * 
     * 
     */
    public List<StopInstancesType> getStopInstances() {
        if (stopInstances == null) {
            stopInstances = new ArrayList<StopInstancesType>();
        }
        return this.stopInstances;
    }

    /**
     * Gets the value of the startInstances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the startInstances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStartInstances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StartInstancesType }
     * 
     * 
     */
    public List<StartInstancesType> getStartInstances() {
        if (startInstances == null) {
            startInstances = new ArrayList<StartInstancesType>();
        }
        return this.startInstances;
    }

    /**
     * Gets the value of the resumeProcesses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resumeProcesses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResumeProcesses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResumeProcessesType }
     * 
     * 
     */
    public List<ResumeProcessesType> getResumeProcesses() {
        if (resumeProcesses == null) {
            resumeProcesses = new ArrayList<ResumeProcessesType>();
        }
        return this.resumeProcesses;
    }

    /**
     * Gets the value of the restoreDBInstanceFromDBSnapshot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restoreDBInstanceFromDBSnapshot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestoreDBInstanceFromDBSnapshot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RestoreDBInstanceFromDBSnapshotType }
     * 
     * 
     */
    public List<RestoreDBInstanceFromDBSnapshotType> getRestoreDBInstanceFromDBSnapshot() {
        if (restoreDBInstanceFromDBSnapshot == null) {
            restoreDBInstanceFromDBSnapshot = new ArrayList<RestoreDBInstanceFromDBSnapshotType>();
        }
        return this.restoreDBInstanceFromDBSnapshot;
    }

    /**
     * Gets the value of the describeKeyPairs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeKeyPairs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeKeyPairs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeKeyPairsType }
     * 
     * 
     */
    public List<DescribeKeyPairsType> getDescribeKeyPairs() {
        if (describeKeyPairs == null) {
            describeKeyPairs = new ArrayList<DescribeKeyPairsType>();
        }
        return this.describeKeyPairs;
    }

    /**
     * Gets the value of the describeSecurityGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeSecurityGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeSecurityGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeSecurityGroupsType }
     * 
     * 
     */
    public List<DescribeSecurityGroupsType> getDescribeSecurityGroups() {
        if (describeSecurityGroups == null) {
            describeSecurityGroups = new ArrayList<DescribeSecurityGroupsType>();
        }
        return this.describeSecurityGroups;
    }

    /**
     * Gets the value of the describeInstances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeInstances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeInstances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeInstancesType }
     * 
     * 
     */
    public List<DescribeInstancesType> getDescribeInstances() {
        if (describeInstances == null) {
            describeInstances = new ArrayList<DescribeInstancesType>();
        }
        return this.describeInstances;
    }

    /**
     * Gets the value of the describeLoadBalancers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeLoadBalancers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeLoadBalancers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeLoadBalancersType }
     * 
     * 
     */
    public List<DescribeLoadBalancersType> getDescribeLoadBalancers() {
        if (describeLoadBalancers == null) {
            describeLoadBalancers = new ArrayList<DescribeLoadBalancersType>();
        }
        return this.describeLoadBalancers;
    }

    /**
     * Gets the value of the describeLaunchConfigurations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeLaunchConfigurations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeLaunchConfigurations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeLaunchConfigurationsType }
     * 
     * 
     */
    public List<DescribeLaunchConfigurationsType> getDescribeLaunchConfigurations() {
        if (describeLaunchConfigurations == null) {
            describeLaunchConfigurations = new ArrayList<DescribeLaunchConfigurationsType>();
        }
        return this.describeLaunchConfigurations;
    }

    /**
     * Gets the value of the describeScalingProcess property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeScalingProcess property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeScalingProcess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeScalingProcessTypes }
     * 
     * 
     */
    public List<DescribeScalingProcessTypes> getDescribeScalingProcess() {
        if (describeScalingProcess == null) {
            describeScalingProcess = new ArrayList<DescribeScalingProcessTypes>();
        }
        return this.describeScalingProcess;
    }

    /**
     * Gets the value of the describeAutoScalingGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeAutoScalingGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeAutoScalingGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeAutoScalingGroupsType }
     * 
     * 
     */
    public List<DescribeAutoScalingGroupsType> getDescribeAutoScalingGroups() {
        if (describeAutoScalingGroups == null) {
            describeAutoScalingGroups = new ArrayList<DescribeAutoScalingGroupsType>();
        }
        return this.describeAutoScalingGroups;
    }

    /**
     * Gets the value of the describeDBSecurityGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeDBSecurityGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeDBSecurityGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeDBSecurityGroupsType }
     * 
     * 
     */
    public List<DescribeDBSecurityGroupsType> getDescribeDBSecurityGroups() {
        if (describeDBSecurityGroups == null) {
            describeDBSecurityGroups = new ArrayList<DescribeDBSecurityGroupsType>();
        }
        return this.describeDBSecurityGroups;
    }

    /**
     * Gets the value of the describeDBInstances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the describeDBInstances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescribeDBInstances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescribeDBInstancesType }
     * 
     * 
     */
    public List<DescribeDBInstancesType> getDescribeDBInstances() {
        if (describeDBInstances == null) {
            describeDBInstances = new ArrayList<DescribeDBInstancesType>();
        }
        return this.describeDBInstances;
    }

	public void setCreateSecurityGroup(
			List<CreateSecurityGroupType> createSecurityGroup) {
		this.createSecurityGroup = createSecurityGroup;
	}

	public void setAddSecurityGroupRule(
			List<AddSecurityGroupRuleType> addSecurityGroupRule) {
		this.addSecurityGroupRule = addSecurityGroupRule;
	}

	public void setCreateKeyPair(List<CreateKeyPairType> createKeyPair) {
		this.createKeyPair = createKeyPair;
	}

	public void setEc2Instance(List<Ec2InstanceType> ec2Instance) {
		this.ec2Instance = ec2Instance;
	}

	public void setLoadBalancer(List<LoadBalancerType> loadBalancer) {
		this.loadBalancer = loadBalancer;
	}

	public void setCreateAppCookieStickinessPolicy(
			List<CreateAppCookieStickinessPolicyType> createAppCookieStickinessPolicy) {
		this.createAppCookieStickinessPolicy = createAppCookieStickinessPolicy;
	}

	public void setCreateLBCookieStickinessPolicy(
			List<CreateLBCookieStickinessPolicyType> createLBCookieStickinessPolicy) {
		this.createLBCookieStickinessPolicy = createLBCookieStickinessPolicy;
	}

	public void setCreateLaunchConfiguration(
			List<CreateLaunchConfigurationType> createLaunchConfiguration) {
		this.createLaunchConfiguration = createLaunchConfiguration;
	}

	public void setCreateAutoScalingGroup(
			List<CreateAutoScalingGroupType> createAutoScalingGroup) {
		this.createAutoScalingGroup = createAutoScalingGroup;
	}

	public void setPutScalingPolicy(List<PutScalingPolicyType> putScalingPolicy) {
		this.putScalingPolicy = putScalingPolicy;
	}

	public void setLaunchRDSInstance(List<CreateDBInstanceType> launchRDSInstance) {
		this.launchRDSInstance = launchRDSInstance;
	}

	public void setPutMetricAlarm(List<PutMetricAlarmType> putMetricAlarm) {
		this.putMetricAlarm = putMetricAlarm;
	}

	public void setCreateDBSecurityGroup(
			List<CreateDBSecurityGroupType> createDBSecurityGroup) {
		this.createDBSecurityGroup = createDBSecurityGroup;
	}

	public void setAuthorizeDBSecurityGroupIngress(
			List<AuthorizeDBSecurityGroupIngressType> authorizeDBSecurityGroupIngress) {
		this.authorizeDBSecurityGroupIngress = authorizeDBSecurityGroupIngress;
	}

	public void setCreateDBInstanceReadReplica(
			List<CreateDBInstanceReadReplicaType> createDBInstanceReadReplica) {
		this.createDBInstanceReadReplica = createDBInstanceReadReplica;
	}

	public void setCreateDBSnapshot(List<CreateDBSnapshotType> createDBSnapshot) {
		this.createDBSnapshot = createDBSnapshot;
	}

	public void setGetMetricStatistics(
			List<GetMetricStatisticsType> getMetricStatistics) {
		this.getMetricStatistics = getMetricStatistics;
	}

	public void setUpdateAutoScalingGroupRequest(
			List<UpdateAutoScalingGroupType> updateAutoScalingGroupRequest) {
		this.updateAutoScalingGroupRequest = updateAutoScalingGroupRequest;
	}

	public void setDeleteAutoScalingGroupRequest(
			List<DeleteAutoScalingGroupType> deleteAutoScalingGroupRequest) {
		this.deleteAutoScalingGroupRequest = deleteAutoScalingGroupRequest;
	}

	public void setDeleteLaunchConfigurationRequest(
			List<DeleteLaunchConfigurationType> deleteLaunchConfigurationRequest) {
		this.deleteLaunchConfigurationRequest = deleteLaunchConfigurationRequest;
	}

	public void setDeleteLoadBalancerRequest(
			List<DeleteLoadBalancerType> deleteLoadBalancerRequest) {
		this.deleteLoadBalancerRequest = deleteLoadBalancerRequest;
	}

	public void setTerminateInstancesRequest(
			List<TerminateInstancesType> terminateInstancesRequest) {
		this.terminateInstancesRequest = terminateInstancesRequest;
	}

	public void setDeleteDBInstanceRequest(
			List<DeleteDBInstanceType> deleteDBInstanceRequest) {
		this.deleteDBInstanceRequest = deleteDBInstanceRequest;
	}

	public void setDeleteKeyPairRequest(List<DeleteKeyPairType> deleteKeyPairRequest) {
		this.deleteKeyPairRequest = deleteKeyPairRequest;
	}

	public void setDeleteSecurityGroupRule(
			List<DeleteSecurityGroupRuleType> deleteSecurityGroupRule) {
		this.deleteSecurityGroupRule = deleteSecurityGroupRule;
	}

	public void setDeleteSecurityGroupRequest(
			List<DeleteSecurityGroupType> deleteSecurityGroupRequest) {
		this.deleteSecurityGroupRequest = deleteSecurityGroupRequest;
	}

	public void setDeleteDBSecurityGroupRequest(
			List<DeleteDBSecurityGroupType> deleteDBSecurityGroupRequest) {
		this.deleteDBSecurityGroupRequest = deleteDBSecurityGroupRequest;
	}

	public void setSuspendProcesses(List<SuspendProcessesType> suspendProcesses) {
		this.suspendProcesses = suspendProcesses;
	}

	public void setStopInstances(List<StopInstancesType> stopInstances) {
		this.stopInstances = stopInstances;
	}

	public void setStartInstances(List<StartInstancesType> startInstances) {
		this.startInstances = startInstances;
	}

	public void setResumeProcesses(List<ResumeProcessesType> resumeProcesses) {
		this.resumeProcesses = resumeProcesses;
	}

	public void setRestoreDBInstanceFromDBSnapshot(
			List<RestoreDBInstanceFromDBSnapshotType> restoreDBInstanceFromDBSnapshot) {
		this.restoreDBInstanceFromDBSnapshot = restoreDBInstanceFromDBSnapshot;
	}

	public void setDescribeKeyPairs(List<DescribeKeyPairsType> describeKeyPairs) {
		this.describeKeyPairs = describeKeyPairs;
	}

	public void setDescribeSecurityGroups(
			List<DescribeSecurityGroupsType> describeSecurityGroups) {
		this.describeSecurityGroups = describeSecurityGroups;
	}

	public void setDescribeInstances(List<DescribeInstancesType> describeInstances) {
		this.describeInstances = describeInstances;
	}

	public void setDescribeLoadBalancers(
			List<DescribeLoadBalancersType> describeLoadBalancers) {
		this.describeLoadBalancers = describeLoadBalancers;
	}

	public void setDescribeLaunchConfigurations(
			List<DescribeLaunchConfigurationsType> describeLaunchConfigurations) {
		this.describeLaunchConfigurations = describeLaunchConfigurations;
	}

	public void setDescribeScalingProcess(
			List<DescribeScalingProcessTypes> describeScalingProcess) {
		this.describeScalingProcess = describeScalingProcess;
	}

	public void setDescribeAutoScalingGroups(
			List<DescribeAutoScalingGroupsType> describeAutoScalingGroups) {
		this.describeAutoScalingGroups = describeAutoScalingGroups;
	}

	public void setDescribeDBSecurityGroups(
			List<DescribeDBSecurityGroupsType> describeDBSecurityGroups) {
		this.describeDBSecurityGroups = describeDBSecurityGroups;
	}

	public void setDescribeDBInstances(
			List<DescribeDBInstancesType> describeDBInstances) {
		this.describeDBInstances = describeDBInstances;
	}

}
