//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.06 at 02:57:13 PM IST 
//


package com.automata.cloudcore.xmlbindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateAutoScalingGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateAutoScalingGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AutoScalingGroupName" type="{}ResourceName"/>
 *         &lt;element name="LaunchConfigurationName" type="{}ResourceName" minOccurs="0"/>
 *         &lt;element name="MinSize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MaxSize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DesiredCapacity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DefaultCooldown" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AvailabilityZones" type="{}AvailabilityZonesType" minOccurs="0"/>
 *         &lt;element name="HealthCheckType" type="{}XmlStringMaxLen32" minOccurs="0"/>
 *         &lt;element name="HealthCheckGracePeriod" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="PlacementGroup" type="{}XmlStringMaxLen255" minOccurs="0"/>
 *         &lt;element name="VPCZoneIdentifier" type="{}XmlStringMaxLen255" minOccurs="0"/>
 *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateAutoScalingGroupType", propOrder = {
    "autoScalingGroupName",
    "launchConfigurationName",
    "minSize",
    "maxSize",
    "desiredCapacity",
    "defaultCooldown",
    "availabilityZones",
    "healthCheckType",
    "healthCheckGracePeriod",
    "placementGroup",
    "vpcZoneIdentifier",
    "region"
})
public class UpdateAutoScalingGroupType {

    @XmlElement(name = "AutoScalingGroupName", required = true)
    protected String autoScalingGroupName;
    @XmlElement(name = "LaunchConfigurationName")
    protected String launchConfigurationName;
    @XmlElement(name = "MinSize")
    protected Integer minSize;
    @XmlElement(name = "MaxSize")
    protected Integer maxSize;
    @XmlElement(name = "DesiredCapacity")
    protected Integer desiredCapacity;
    @XmlElement(name = "DefaultCooldown")
    protected Integer defaultCooldown;
    @XmlElement(name = "AvailabilityZones")
    protected AvailabilityZonesType availabilityZones;
    @XmlElement(name = "HealthCheckType")
    protected String healthCheckType;
    @XmlElement(name = "HealthCheckGracePeriod")
    protected Integer healthCheckGracePeriod;
    @XmlElement(name = "PlacementGroup")
    protected String placementGroup;
    @XmlElement(name = "VPCZoneIdentifier")
    protected String vpcZoneIdentifier;
    @XmlElement(name = "Region", required = true)
    protected String region;

    /**
     * Gets the value of the autoScalingGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoScalingGroupName() {
        return autoScalingGroupName;
    }

    /**
     * Sets the value of the autoScalingGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoScalingGroupName(String value) {
        this.autoScalingGroupName = value;
    }

    /**
     * Gets the value of the launchConfigurationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaunchConfigurationName() {
        return launchConfigurationName;
    }

    /**
     * Sets the value of the launchConfigurationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaunchConfigurationName(String value) {
        this.launchConfigurationName = value;
    }

    /**
     * Gets the value of the minSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinSize() {
        return minSize;
    }

    /**
     * Sets the value of the minSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinSize(Integer value) {
        this.minSize = value;
    }

    /**
     * Gets the value of the maxSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxSize() {
        return maxSize;
    }

    /**
     * Sets the value of the maxSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxSize(Integer value) {
        this.maxSize = value;
    }

    /**
     * Gets the value of the desiredCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDesiredCapacity() {
        return desiredCapacity;
    }

    /**
     * Sets the value of the desiredCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDesiredCapacity(Integer value) {
        this.desiredCapacity = value;
    }

    /**
     * Gets the value of the defaultCooldown property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDefaultCooldown() {
        return defaultCooldown;
    }

    /**
     * Sets the value of the defaultCooldown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDefaultCooldown(Integer value) {
        this.defaultCooldown = value;
    }

    /**
     * Gets the value of the availabilityZones property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityZonesType }
     *     
     */
    public AvailabilityZonesType getAvailabilityZones() {
        return availabilityZones;
    }

    /**
     * Sets the value of the availabilityZones property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityZonesType }
     *     
     */
    public void setAvailabilityZones(AvailabilityZonesType value) {
        this.availabilityZones = value;
    }

    /**
     * Gets the value of the healthCheckType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthCheckType() {
        return healthCheckType;
    }

    /**
     * Sets the value of the healthCheckType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthCheckType(String value) {
        this.healthCheckType = value;
    }

    /**
     * Gets the value of the healthCheckGracePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHealthCheckGracePeriod() {
        return healthCheckGracePeriod;
    }

    /**
     * Sets the value of the healthCheckGracePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHealthCheckGracePeriod(Integer value) {
        this.healthCheckGracePeriod = value;
    }

    /**
     * Gets the value of the placementGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlacementGroup() {
        return placementGroup;
    }

    /**
     * Sets the value of the placementGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlacementGroup(String value) {
        this.placementGroup = value;
    }

    /**
     * Gets the value of the vpcZoneIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVPCZoneIdentifier() {
        return vpcZoneIdentifier;
    }

    /**
     * Sets the value of the vpcZoneIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVPCZoneIdentifier(String value) {
        this.vpcZoneIdentifier = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

}
